{
 "title": "alert-manager",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "ds", "label": "data source", "query": "prometheus" },
   { "name": "cluster", "label": "Cluster", "query": { "query": "label_values(flag, cluster)" } },
   {
    "name": "region",
    "label": "Region",
    "query": {
     "query": "label_values(go_info{cluster=~\"$cluster\"}, region)"
    }
   },
   {
    "name": "env",
    "label": "Env",
    "query": {
     "query": "label_values(go_info{cluster=~\"$cluster\",region=~\"$region\"}, env)"
    }
   },
   {
    "name": "instance",
    "label": "Instance",
    "query": {
     "query": "label_values(go_info{cluster=~\"$cluster\",region=~\"$region\",env=~\"$env\",role=\"alert-manager\"}, instance)"
    }
   },
   {
    "name": "container_ip",
    "label": "Container IP",
    "query": {
     "query": "label_values(go_info{cluster=~\"$cluster\",region=~\"$region\",env=~\"$env\",role=\"alert-manager\"}, container_ip)"
    }
   },
   {
    "name": "container_name",
    "label": "Container Name",
    "query": {
     "query": "label_values(go_info{cluster=~\"$cluster\",region=~\"$region\",env=~\"$env\",role=\"alert-manager\"}, container_name)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "CPU time (system + user)",
   "type": "timeseries",
   "description": "process_cpu_seconds_total = process_cpu_seconds_system_total + \nprocess_cpu_seconds_user_total\n\nIf only 1 cpu core, max value is 100%; 2 cpu's max value is 200%.",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "(sum by ()(rate(process_cpu_seconds_system_total{cluster=~\"$cluster\",region=~\"$region\",env=~\"$env\",role=\"alert-manager\",instance=~\"$instance\",container_ip=~\"$container_ip\",container_name=~\"$container_name\"}[1m])))",
     "legendFormat": "process_cpu_seconds_system_total"
    },
    {
     "expr": "(sum by ()(rate(process_cpu_seconds_user_total{cluster=~\"$cluster\",region=~\"$region\",env=~\"$env\",role=\"alert-manager\",instance=~\"$instance\",container_ip=~\"$container_ip\",container_name=~\"$container_name\"}[1m])))",
     "legendFormat": "process_cpu_seconds_user_total"
    }
   ]
  },
  {
   "title": "alertmanager_alerts_invalid_total/s",
   "type": "timeseries",
   "description": "alertmanager_alerts_invalid_total",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by () (rate(alertmanager_alerts_invalid_total{cluster=~\"$cluster\",region=~\"$region\",env=~\"$env\",role=\"alert-manager\",instance=~\"$instance\",container_ip=~\"$container_ip\",container_name=~\"$container_name\"}[1m]))",
     "legendFormat": "alertmanager_alerts_invalid_total"
    }
   ]
  },
  {
   "title": "alertmanager_alerts_received_total/s",
   "type": "timeseries",
   "description": "alertmanager_alerts_received_total",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by () (rate(alertmanager_alerts_received_total{cluster=~\"$cluster\",region=~\"$region\",env=~\"$env\",role=\"alert-manager\",instance=~\"$instance\",container_ip=~\"$container_ip\",container_name=~\"$container_name\"}[1m]))",
     "legendFormat": "alertmanager_alerts_received_total"
    }
   ]
  },
  {
   "title": "alertmanager_cluster_alive_messages_total/s",
   "type": "timeseries",
   "description": "alertmanager_cluster_alive_messages_total",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by () (rate(alertmanager_cluster_alive_messages_total{cluster=~\"$cluster\",region=~\"$region\",env=~\"$env\",role=\"alert-manager\",instance=~\"$instance\",container_ip=~\"$container_ip\",container_name=~\"$container_name\"}[1m]))",
     "legendFormat": "alertmanager_cluster_alive_messages_total"
    }
   ]
  },
  {
   "title": "alertmanager_cluster_messages_received_size_total/s",
   "type": "timeseries",
   "description": "alertmanager_cluster_messages_received_size_total",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by () (rate(alertmanager_cluster_messages_received_size_total{cluster=~\"$cluster\",region=~\"$region\",env=~\"$env\",role=\"alert-manager\",instance=~\"$instance\",container_ip=~\"$container_ip\",container_name=~\"$container_name\"}[1m]))",
     "legendFormat": "alertmanager_cluster_messages_received_size_total"
    }
   ]
  },
  {
   "title": "alertmanager_cluster_messages_received_total/s",
   "type": "timeseries",
   "description": "alertmanager_cluster_messages_received_total",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by () (rate(alertmanager_cluster_messages_received_total{cluster=~\"$cluster\",region=~\"$region\",env=~\"$env\",role=\"alert-manager\",instance=~\"$instance\",container_ip=~\"$container_ip\",container_name=~\"$container_name\"}[1m]))",
     "legendFormat": "alertmanager_cluster_messages_received_total"
    }
   ]
  },
  {
   "title": "alertmanager_cluster_messages_sent_size_total/s",
   "type": "timeseries",
   "description": "alertmanager_cluster_messages_sent_size_total",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by () (rate(alertmanager_cluster_messages_sent_size_total{cluster=~\"$cluster\",region=~\"$region\",env=~\"$env\",role=\"alert-manager\",instance=~\"$instance\",container_ip=~\"$container_ip\",container_name=~\"$container_name\"}[1m]))",
     "legendFormat": "alertmanager_cluster_messages_sent_size_total"
    }
   ]
  },
  {
   "title": "alertmanager_cluster_messages_sent_total/s",
   "type": "timeseries",
   "description": "alertmanager_cluster_messages_sent_total",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by () (rate(alertmanager_cluster_messages_sent_total{cluster=~\"$cluster\",region=~\"$region\",env=~\"$env\",role=\"alert-manager\",instance=~\"$instance\",container_ip=~\"$container_ip\",container_name=~\"$container_name\"}[1m]))",
     "legendFormat": "alertmanager_cluster_messages_sent_total"
    }
   ]
  },
  {
   "title": "alertmanager_http_concurrency_limit_exceeded_total/s",
   "type": "timeseries",
   "description": "alertmanager_http_concurrency_limit_exceeded_total",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by () (rate(alertmanager_http_concurrency_limit_exceeded_total{cluster=~\"$cluster\",region=~\"$region\",env=~\"$env\",role=\"alert-manager\",instance=~\"$instance\",container_ip=~\"$container_ip\",container_name=~\"$container_name\"}[1m]))",
     "legendFormat": "alertmanager_http_concurrency_limit_exceeded_total"
    }
   ]
  },
  {
   "title": "alertmanager_notification_requests_failed_total/s",
   "type": "timeseries",
   "description": "alertmanager_notification_requests_failed_total",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by () (rate(alertmanager_notification_requests_failed_total{cluster=~\"$cluster\",region=~\"$region\",env=~\"$env\",role=\"alert-manager\",instance=~\"$instance\",container_ip=~\"$container_ip\",container_name=~\"$container_name\"}[1m]))",
     "legendFormat": "alertmanager_notification_requests_failed_total"
    }
   ]
  },
  {
   "title": "alertmanager_notification_requests_total/s",
   "type": "timeseries",
   "description": "alertmanager_notification_requests_total",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by () (rate(alertmanager_notification_requests_total{cluster=~\"$cluster\",region=~\"$region\",env=~\"$env\",role=\"alert-manager\",instance=~\"$instance\",container_ip=~\"$container_ip\",container_name=~\"$container_name\"}[1m]))",
     "legendFormat": "alertmanager_notification_requests_total"
    }
   ]
  },
  {
   "title": "alertmanager_notifications_failed_total/s",
   "type": "timeseries",
   "description": "alertmanager_notifications_failed_total",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by () (rate(alertmanager_notifications_failed_total{cluster=~\"$cluster\",region=~\"$region\",env=~\"$env\",role=\"alert-manager\",instance=~\"$instance\",container_ip=~\"$container_ip\",container_name=~\"$container_name\"}[1m]))",
     "legendFormat": "alertmanager_notifications_failed_total"
    }
   ]
  },
  {
   "title": "alertmanager_notifications_total/s",
   "type": "timeseries",
   "description": "alertmanager_notifications_total",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by () (rate(alertmanager_notifications_total{cluster=~\"$cluster\",region=~\"$region\",env=~\"$env\",role=\"alert-manager\",instance=~\"$instance\",container_ip=~\"$container_ip\",container_name=~\"$container_name\"}[1m]))",
     "legendFormat": "alertmanager_notifications_total"
    }
   ]
  },
  {
   "title": "alertmanager_oversized_gossip_message_dropped_total/s",
   "type": "timeseries",
   "description": "alertmanager_oversized_gossip_message_dropped_total",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by () (rate(alertmanager_oversized_gossip_message_dropped_total{cluster=~\"$cluster\",region=~\"$region\",env=~\"$env\",role=\"alert-manager\",instance=~\"$instance\",container_ip=~\"$container_ip\",container_name=~\"$container_name\"}[1m]))",
     "legendFormat": "alertmanager_oversized_gossip_message_dropped_total"
    }
   ]
  },
  {
   "title": "alertmanager_oversized_gossip_message_failure_total/s",
   "type": "timeseries",
   "description": "alertmanager_oversized_gossip_message_failure_total",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by () (rate(alertmanager_oversized_gossip_message_failure_total{cluster=~\"$cluster\",region=~\"$region\",env=~\"$env\",role=\"alert-manager\",instance=~\"$instance\",container_ip=~\"$container_ip\",container_name=~\"$container_name\"}[1m]))",
     "legendFormat": "alertmanager_oversized_gossip_message_failure_total"
    }
   ]
  },
  {
   "title": "alertmanager_oversized_gossip_message_sent_total/s",
   "type": "timeseries",
   "description": "alertmanager_oversized_gossip_message_sent_total",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by () (rate(alertmanager_oversized_gossip_message_sent_total{cluster=~\"$cluster\",region=~\"$region\",env=~\"$env\",role=\"alert-manager\",instance=~\"$instance\",container_ip=~\"$container_ip\",container_name=~\"$container_name\"}[1m]))",
     "legendFormat": "alertmanager_oversized_gossip_message_sent_total"
    }
   ]
  },
  {
   "title": "net_conntrack_dialer_conn_attempted_total/s",
   "type": "timeseries",
   "description": "net_conntrack_dialer_conn_attempted_total",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by () (rate(net_conntrack_dialer_conn_attempted_total{cluster=~\"$cluster\",region=~\"$region\",env=~\"$env\",role=\"alert-manager\",instance=~\"$instance\",container_ip=~\"$container_ip\",container_name=~\"$container_name\"}[1m]))",
     "legendFormat": "net_conntrack_dialer_conn_attempted_total"
    }
   ]
  },
  {
   "title": "net_conntrack_dialer_conn_closed_total/s",
   "type": "timeseries",
   "description": "net_conntrack_dialer_conn_closed_total",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by () (rate(net_conntrack_dialer_conn_closed_total{cluster=~\"$cluster\",region=~\"$region\",env=~\"$env\",role=\"alert-manager\",instance=~\"$instance\",container_ip=~\"$container_ip\",container_name=~\"$container_name\"}[1m]))",
     "legendFormat": "net_conntrack_dialer_conn_closed_total"
    }
   ]
  },
  {
   "title": "net_conntrack_dialer_conn_established_total/s",
   "type": "timeseries",
   "description": "net_conntrack_dialer_conn_established_total",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by () (rate(net_conntrack_dialer_conn_established_total{cluster=~\"$cluster\",region=~\"$region\",env=~\"$env\",role=\"alert-manager\",instance=~\"$instance\",container_ip=~\"$container_ip\",container_name=~\"$container_name\"}[1m]))",
     "legendFormat": "net_conntrack_dialer_conn_established_total"
    }
   ]
  },
  {
   "title": "net_conntrack_dialer_conn_failed_total/s",
   "type": "timeseries",
   "description": "net_conntrack_dialer_conn_failed_total",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by () (rate(net_conntrack_dialer_conn_failed_total{cluster=~\"$cluster\",region=~\"$region\",env=~\"$env\",role=\"alert-manager\",instance=~\"$instance\",container_ip=~\"$container_ip\",container_name=~\"$container_name\"}[1m]))",
     "legendFormat": "net_conntrack_dialer_conn_failed_total"
    }
   ]
  },
  {
   "title": "promhttp_metric_handler_requests_total/s",
   "type": "timeseries",
   "description": "promhttp_metric_handler_requests_total",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by () (rate(promhttp_metric_handler_requests_total{cluster=~\"$cluster\",region=~\"$region\",env=~\"$env\",role=\"alert-manager\",instance=~\"$instance\",container_ip=~\"$container_ip\",container_name=~\"$container_name\"}[1m]))",
     "legendFormat": "promhttp_metric_handler_requests_total"
    }
   ]
  },
  {
   "title": "alertmanager_silences",
   "type": "timeseries",
   "description": "alertmanager_silences",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(alertmanager_silences{cluster=~\"$cluster\",region=~\"$region\",env=~\"$env\",role=\"alert-manager\",instance=~\"$instance\",container_ip=~\"$container_ip\",container_name=~\"$container_name\"})",
     "legendFormat": "alertmanager_silences"
    }
   ]
  },
  {
   "title": "alertmanager_alerts",
   "type": "timeseries",
   "description": "alertmanager_alerts",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 49 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(alertmanager_alerts{cluster=~\"$cluster\",region=~\"$region\",env=~\"$env\",role=\"alert-manager\",instance=~\"$instance\",container_ip=~\"$container_ip\",container_name=~\"$container_name\"})",
     "legendFormat": "alertmanager_alerts"
    }
   ]
  },
  {
   "title": "alertmanager_http_requests_in_flight",
   "type": "timeseries",
   "description": "alertmanager_http_requests_in_flight",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 49 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(alertmanager_http_requests_in_flight{cluster=~\"$cluster\",region=~\"$region\",env=~\"$env\",role=\"alert-manager\",instance=~\"$instance\",container_ip=~\"$container_ip\",container_name=~\"$container_name\"})",
     "legendFormat": "alertmanager_http_requests_in_flight"
    }
   ]
  },
  {
   "title": "alertmanager_marked_alerts",
   "type": "timeseries",
   "description": "alertmanager_marked_alerts",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 49 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(alertmanager_marked_alerts{cluster=~\"$cluster\",region=~\"$region\",env=~\"$env\",role=\"alert-manager\",instance=~\"$instance\",container_ip=~\"$container_ip\",container_name=~\"$container_name\"})",
     "legendFormat": "alertmanager_marked_alerts"
    }
   ]
  },
  {
   "title": "alertmanager_cluster_pings_seconds_bucket",
   "type": "heatmap",
   "description": "alertmanager_cluster_pings_seconds_bucket",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 49 },
   "targets": [
    {
     "expr": "sum(increase(label_replace(alertmanager_cluster_pings_seconds_bucket{cluster=~\"$cluster\",region=~\"$region\",env=~\"$env\",role=\"alert-manager\",instance=~\"$instance\",container_ip=~\"$container_ip\",container_name=~\"$container_name\"}, \"le\", \"$1\", \"vmrange\", \"([^\\\\n]+)\\\\.\\\\.\\\\.([^\\\\n]+)\")[1m])) by (le)",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "alertmanager_http_request_duration_seconds_bucket",
   "type": "heatmap",
   "description": "alertmanager_http_request_duration_seconds_bucket",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 57 },
   "targets": [
    {
     "expr": "sum(increase(label_replace(alertmanager_http_request_duration_seconds_bucket{cluster=~\"$cluster\",region=~\"$region\",env=~\"$env\",role=\"alert-manager\",instance=~\"$instance\",container_ip=~\"$container_ip\",container_name=~\"$container_name\"}, \"le\", \"$1\", \"vmrange\", \"([^\\\\n]+)\\\\.\\\\.\\\\.([^\\\\n]+)\")[1m])) by (le)",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "alertmanager_http_response_size_bytes_bucket",
   "type": "heatmap",
   "description": "alertmanager_http_response_size_bytes_bucket",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 57 },
   "targets": [
    {
     "expr": "sum(increase(label_replace(alertmanager_http_response_size_bytes_bucket{cluster=~\"$cluster\",region=~\"$region\",env=~\"$env\",role=\"alert-manager\",instance=~\"$instance\",container_ip=~\"$container_ip\",container_name=~\"$container_name\"}, \"le\", \"$1\", \"vmrange\", \"([^\\\\n]+)\\\\.\\\\.\\\\.([^\\\\n]+)\")[1m])) by (le)",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "alertmanager_nflog_query_duration_seconds_bucket",
   "type": "heatmap",
   "description": "alertmanager_nflog_query_duration_seconds_bucket",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 57 },
   "targets": [
    {
     "expr": "sum(increase(label_replace(alertmanager_nflog_query_duration_seconds_bucket{cluster=~\"$cluster\",region=~\"$region\",env=~\"$env\",role=\"alert-manager\",instance=~\"$instance\",container_ip=~\"$container_ip\",container_name=~\"$container_name\"}, \"le\", \"$1\", \"vmrange\", \"([^\\\\n]+)\\\\.\\\\.\\\\.([^\\\\n]+)\")[1m])) by (le)",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "alertmanager_notification_latency_seconds_bucket",
   "type": "heatmap",
   "description": "alertmanager_notification_latency_seconds_bucket",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 57 },
   "targets": [
    {
     "expr": "sum(increase(label_replace(alertmanager_notification_latency_seconds_bucket{cluster=~\"$cluster\",region=~\"$region\",env=~\"$env\",role=\"alert-manager\",instance=~\"$instance\",container_ip=~\"$container_ip\",container_name=~\"$container_name\"}, \"le\", \"$1\", \"vmrange\", \"([^\\\\n]+)\\\\.\\\\.\\\\.([^\\\\n]+)\")[1m])) by (le)",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "alertmanager_oversize_gossip_message_duration_seconds_bucket",
   "type": "heatmap",
   "description": "alertmanager_oversize_gossip_message_duration_seconds_bucket",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 65 },
   "targets": [
    {
     "expr": "sum(increase(label_replace(alertmanager_oversize_gossip_message_duration_seconds_bucket{cluster=~\"$cluster\",region=~\"$region\",env=~\"$env\",role=\"alert-manager\",instance=~\"$instance\",container_ip=~\"$container_ip\",container_name=~\"$container_name\"}, \"le\", \"$1\", \"vmrange\", \"([^\\\\n]+)\\\\.\\\\.\\\\.([^\\\\n]+)\")[1m])) by (le)",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "alertmanager_silences_query_duration_seconds_bucket",
   "type": "heatmap",
   "description": "alertmanager_silences_query_duration_seconds_bucket",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 65 },
   "targets": [
    {
     "expr": "sum(increase(label_replace(alertmanager_silences_query_duration_seconds_bucket{cluster=~\"$cluster\",region=~\"$region\",env=~\"$env\",role=\"alert-manager\",instance=~\"$instance\",container_ip=~\"$container_ip\",container_name=~\"$container_name\"}, \"le\", \"$1\", \"vmrange\", \"([^\\\\n]+)\\\\.\\\\.\\\\.([^\\\\n]+)\")[1m])) by (le)",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "not added metrics",
   "type": "text",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 65 },
   "options": {
    "content": "* alertmanager_build_info\n* alertmanager_cluster_peer_info\n"
   }
  }
 ]
}