{
 "title": "vm-storage",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "ds", "label": "data source", "query": "prometheus" },
   { "name": "cluster", "label": "Cluster", "query": { "query": "label_values(flag, cluster)" } },
   {
    "name": "region",
    "label": "Region",
    "query": {
     "query": "label_values(go_info{cluster=~\"$cluster\"}, region)"
    }
   },
   {
    "name": "env",
    "label": "Env",
    "query": {
     "query": "label_values(go_info{cluster=~\"$cluster\",region=~\"$region\"}, env)"
    }
   },
   {
    "name": "instance",
    "label": "Instance",
    "query": {
     "query": "label_values(go_info{cluster=~\"$cluster\",region=~\"$region\",env=~\"$env\",role=\"vm-storage\"}, instance)"
    }
   },
   {
    "name": "container_ip",
    "label": "Container IP",
    "query": {
     "query": "label_values(go_info{cluster=~\"$cluster\",region=~\"$region\",env=~\"$env\",role=\"vm-storage\"}, container_ip)"
    }
   },
   {
    "name": "container_name",
    "label": "Container Name",
    "query": {
     "query": "label_values(go_info{cluster=~\"$cluster\",region=~\"$region\",env=~\"$env\",role=\"vm-storage\"}, container_name)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "CPU time (system + user)",
   "type": "timeseries",
   "description": "process_cpu_seconds_total = process_cpu_seconds_system_total + \nprocess_cpu_seconds_user_total\n\nIf only 1 cpu core, max value is 100%; 2 cpu's max value is 200%.",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "(sum by ()(rate(process_cpu_seconds_system_total{cluster=~\"$cluster\",region=~\"$region\",env=~\"$env\",role=\"vm-storage\",instance=~\"$instance\",container_ip=~\"$container_ip\",container_name=~\"$container_name\"}[1m])))",
     "legendFormat": "process_cpu_seconds_system_total"
    },
    {
     "expr": "(sum by ()(rate(process_cpu_seconds_user_total{cluster=~\"$cluster\",region=~\"$region\",env=~\"$env\",role=\"vm-storage\",instance=~\"$instance\",container_ip=~\"$container_ip\",container_name=~\"$container_name\"}[1m])))",
     "legendFormat": "process_cpu_seconds_user_total"
    }
   ]
  },
  {
   "title": "vm_assisted_merges_total/s",
   "type": "timeseries",
   "description": "vm_assisted_merges_total",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by () (rate(vm_assisted_merges_total{cluster=~\"$cluster\",region=~\"$region\",env=~\"$env\",role=\"vm-storage\",instance=~\"$instance\",container_ip=~\"$container_ip\",container_name=~\"$container_name\"}[1m]))",
     "legendFormat": "vm_assisted_merges_total"
    }
   ]
  },
  {
   "title": "vm_cache_collisions_total/s",
   "type": "timeseries",
   "description": "vm_cache_collisions_total",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by () (rate(vm_cache_collisions_total{cluster=~\"$cluster\",region=~\"$region\",env=~\"$env\",role=\"vm-storage\",instance=~\"$instance\",container_ip=~\"$container_ip\",container_name=~\"$container_name\"}[1m]))",
     "legendFormat": "vm_cache_collisions_total"
    }
   ]
  },
  {
   "title": "vm_cache_misses_total/s",
   "type": "timeseries",
   "description": "vm_cache_misses_total",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by () (rate(vm_cache_misses_total{cluster=~\"$cluster\",region=~\"$region\",env=~\"$env\",role=\"vm-storage\",instance=~\"$instance\",container_ip=~\"$container_ip\",container_name=~\"$container_name\"}[1m]))",
     "legendFormat": "vm_cache_misses_total"
    }
   ]
  },
  {
   "title": "vm_cache_requests_total/s",
   "type": "timeseries",
   "description": "vm_cache_requests_total",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by () (rate(vm_cache_requests_total{cluster=~\"$cluster\",region=~\"$region\",env=~\"$env\",role=\"vm-storage\",instance=~\"$instance\",container_ip=~\"$container_ip\",container_name=~\"$container_name\"}[1m]))",
     "legendFormat": "vm_cache_requests_total"
    }
   ]
  },
  {
   "title": "vm_deduplicated_samples_total/s",
   "type": "timeseries",
   "description": "vm_deduplicated_samples_total",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by () (rate(vm_deduplicated_samples_total{cluster=~\"$cluster\",region=~\"$region\",env=~\"$env\",role=\"vm-storage\",instance=~\"$instance\",container_ip=~\"$container_ip\",container_name=~\"$container_name\"}[1m]))",
     "legendFormat": "vm_deduplicated_samples_total"
    }
   ]
  },
  {
   "title": "vm_deleted_metrics_total/s",
   "type": "timeseries",
   "description": "vm_deleted_metrics_total",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by () (rate(vm_deleted_metrics_total{cluster=~\"$cluster\",region=~\"$region\",env=~\"$env\",role=\"vm-storage\",instance=~\"$instance\",container_ip=~\"$container_ip\",container_name=~\"$container_name\"}[1m]))",
     "legendFormat": "vm_deleted_metrics_total"
    }
   ]
  },
  {
   "title": "vm_http_request_errors_total/s",
   "type": "timeseries",
   "description": "vm_http_request_errors_total",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by () (rate(vm_http_request_errors_total{cluster=~\"$cluster\",region=~\"$region\",env=~\"$env\",role=\"vm-storage\",instance=~\"$instance\",container_ip=~\"$container_ip\",container_name=~\"$container_name\"}[1m]))",
     "legendFormat": "vm_http_request_errors_total"
    }
   ]
  },
  {
   "title": "vm_http_requests_total/s",
   "type": "timeseries",
   "description": "vm_http_requests_total",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by () (rate(vm_http_requests_total{cluster=~\"$cluster\",region=~\"$region\",env=~\"$env\",role=\"vm-storage\",instance=~\"$instance\",container_ip=~\"$container_ip\",container_name=~\"$container_name\"}[1m]))",
     "legendFormat": "vm_http_requests_total"
    }
   ]
  },
  {
   "title": "vm_log_messages_total/s",
   "type": "timeseries",
   "description": "vm_log_messages_total",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by () (rate(vm_log_messages_total{cluster=~\"$cluster\",region=~\"$region\",env=~\"$env\",role=\"vm-storage\",instance=~\"$instance\",container_ip=~\"$container_ip\",container_name=~\"$container_name\"}[1m]))",
     "legendFormat": "vm_log_messages_total"
    }
   ]
  },
  {
   "title": "vm_merges_total/s",
   "type": "timeseries",
   "description": "vm_merges_total",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by () (rate(vm_merges_total{cluster=~\"$cluster\",region=~\"$region\",env=~\"$env\",role=\"vm-storage\",instance=~\"$instance\",container_ip=~\"$container_ip\",container_name=~\"$container_name\"}[1m]))",
     "legendFormat": "vm_merges_total"
    }
   ]
  },
  {
   "title": "vm_protoparser_blocks_read_total/s",
   "type": "timeseries",
   "description": "vm_protoparser_blocks_read_total",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by () (rate(vm_protoparser_blocks_read_total{cluster=~\"$cluster\",region=~\"$region\",env=~\"$env\",role=\"vm-storage\",instance=~\"$instance\",container_ip=~\"$container_ip\",container_name=~\"$container_name\"}[1m]))",
     "legendFormat": "vm_protoparser_blocks_read_total"
    }
   ]
  },
  {
   "title": "vm_protoparser_parse_errors_total/s",
   "type": "timeseries",
   "description": "vm_protoparser_parse_errors_total",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by () (rate(vm_protoparser_parse_errors_total{cluster=~\"$cluster\",region=~\"$region\",env=~\"$env\",role=\"vm-storage\",instance=~\"$instance\",container_ip=~\"$container_ip\",container_name=~\"$container_name\"}[1m]))",
     "legendFormat": "vm_protoparser_parse_errors_total"
    }
   ]
  },
  {
   "title": "vm_protoparser_process_errors_total/s",
   "type": "timeseries",
   "description": "vm_protoparser_process_errors_total",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by () (rate(vm_protoparser_process_errors_total{cluster=~\"$cluster\",region=~\"$region\",env=~\"$env\",role=\"vm-storage\",instance=~\"$instance\",container_ip=~\"$container_ip\",container_name=~\"$container_name\"}[1m]))",
     "legendFormat": "vm_protoparser_process_errors_total"
    }
   ]
  },
  {
   "title": "vm_protoparser_read_errors_total/s",
   "type": "timeseries",
   "description": "vm_protoparser_read_errors_total",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by () (rate(vm_protoparser_read_errors_total{cluster=~\"$cluster\",region=~\"$region\",env=~\"$env\",role=\"vm-storage\",instance=~\"$instance\",container_ip=~\"$container_ip\",container_name=~\"$container_name\"}[1m]))",
     "legendFormat": "vm_protoparser_read_errors_total"
    }
   ]
  },
  {
   "title": "vm_protoparser_rows_read_total/s",
   "type": "timeseries",
   "description": "vm_protoparser_rows_read_total",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by () (rate(vm_protoparser_rows_read_total{cluster=~\"$cluster\",region=~\"$region\",env=~\"$env\",role=\"vm-storage\",instance=~\"$instance\",container_ip=~\"$container_ip\",container_name=~\"$container_name\"}[1m]))",
     "legendFormat": "vm_protoparser_rows_read_total"
    }
   ]
  },
  {
   "title": "vm_protoparser_write_errors_total/s",
   "type": "timeseries",
   "description": "vm_protoparser_write_errors_total",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by () (rate(vm_protoparser_write_errors_total{cluster=~\"$cluster\",region=~\"$region\",env=~\"$env\",role=\"vm-storage\",instance=~\"$instance\",container_ip=~\"$container_ip\",container_name=~\"$container_name\"}[1m]))",
     "legendFormat": "vm_protoparser_write_errors_total"
    }
   ]
  },
  {
   "title": "vm_rows_deleted_total/s",
   "type": "timeseries",
   "description": "vm_rows_deleted_total",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by () (rate(vm_rows_deleted_total{cluster=~\"$cluster\",region=~\"$region\",env=~\"$env\",role=\"vm-storage\",instance=~\"$instance\",container_ip=~\"$container_ip\",container_name=~\"$container_name\"}[1m]))",
     "legendFormat": "vm_rows_deleted_total"
    }
   ]
  },
  {
   "title": "vm_rows_ignored_total/s",
   "type": "timeseries",
   "description": "vm_rows_ignored_total",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by () (rate(vm_rows_ignored_total{cluster=~\"$cluster\",region=~\"$region\",env=~\"$env\",role=\"vm-storage\",instance=~\"$instance\",container_ip=~\"$container_ip\",container_name=~\"$container_name\"}[1m]))",
     "legendFormat": "vm_rows_ignored_total"
    }
   ]
  },
  {
   "title": "vm_rows_invalid_total/s",
   "type": "timeseries",
   "description": "vm_rows_invalid_total",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by () (rate(vm_rows_invalid_total{cluster=~\"$cluster\",region=~\"$region\",env=~\"$env\",role=\"vm-storage\",instance=~\"$instance\",container_ip=~\"$container_ip\",container_name=~\"$container_name\"}[1m]))",
     "legendFormat": "vm_rows_invalid_total"
    }
   ]
  },
  {
   "title": "vm_rows_merged_total/s",
   "type": "timeseries",
   "description": "vm_rows_merged_total",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by () (rate(vm_rows_merged_total{cluster=~\"$cluster\",region=~\"$region\",env=~\"$env\",role=\"vm-storage\",instance=~\"$instance\",container_ip=~\"$container_ip\",container_name=~\"$container_name\"}[1m]))",
     "legendFormat": "vm_rows_merged_total"
    }
   ]
  },
  {
   "title": "vm_tcplistener_accepts_total/s",
   "type": "timeseries",
   "description": "vm_tcplistener_accepts_total",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by () (rate(vm_tcplistener_accepts_total{cluster=~\"$cluster\",region=~\"$region\",env=~\"$env\",role=\"vm-storage\",instance=~\"$instance\",container_ip=~\"$container_ip\",container_name=~\"$container_name\"}[1m]))",
     "legendFormat": "vm_tcplistener_accepts_total"
    }
   ]
  },
  {
   "title": "vm_tcplistener_errors_total/s",
   "type": "timeseries",
   "description": "vm_tcplistener_errors_total",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 49 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by () (rate(vm_tcplistener_errors_total{cluster=~\"$cluster\",region=~\"$region\",env=~\"$env\",role=\"vm-storage\",instance=~\"$instance\",container_ip=~\"$container_ip\",container_name=~\"$container_name\"}[1m]))",
     "legendFormat": "vm_tcplistener_errors_total"
    }
   ]
  },
  {
   "title": "vm_tcplistener_read_bytes_total/s",
   "type": "timeseries",
   "description": "vm_tcplistener_read_bytes_total",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 49 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum by () (rate(vm_tcplistener_read_bytes_total{cluster=~\"$cluster\",region=~\"$region\",env=~\"$env\",role=\"vm-storage\",instance=~\"$instance\",container_ip=~\"$container_ip\",container_name=~\"$container_name\"}[1m]))",
     "legendFormat": "vm_tcplistener_read_bytes_total"
    }
   ]
  },
  {
   "title": "vm_tcplistener_read_calls_total/s",
   "type": "timeseries",
   "description": "vm_tcplistener_read_calls_total",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 49 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by () (rate(vm_tcplistener_read_calls_total{cluster=~\"$cluster\",region=~\"$region\",env=~\"$env\",role=\"vm-storage\",instance=~\"$instance\",container_ip=~\"$container_ip\",container_name=~\"$container_name\"}[1m]))",
     "legendFormat": "vm_tcplistener_read_calls_total"
    }
   ]
  },
  {
   "title": "vm_tcplistener_read_timeouts_total/s",
   "type": "timeseries",
   "description": "vm_tcplistener_read_timeouts_total",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 49 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by () (rate(vm_tcplistener_read_timeouts_total{cluster=~\"$cluster\",region=~\"$region\",env=~\"$env\",role=\"vm-storage\",instance=~\"$instance\",container_ip=~\"$container_ip\",container_name=~\"$container_name\"}[1m]))",
     "legendFormat": "vm_tcplistener_read_timeouts_total"
    }
   ]
  },
  {
   "title": "vm_tcplistener_write_calls_total/s",
   "type": "timeseries",
   "description": "vm_tcplistener_write_calls_total",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 57 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by () (rate(vm_tcplistener_write_calls_total{cluster=~\"$cluster\",region=~\"$region\",env=~\"$env\",role=\"vm-storage\",instance=~\"$instance\",container_ip=~\"$container_ip\",container_name=~\"$container_name\"}[1m]))",
     "legendFormat": "vm_tcplistener_write_calls_total"
    }
   ]
  },
  {
   "title": "vm_tcplistener_write_timeouts_total/s",
   "type": "timeseries",
   "description": "vm_tcplistener_write_timeouts_total",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 57 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by () (rate(vm_tcplistener_write_timeouts_total{cluster=~\"$cluster\",region=~\"$region\",env=~\"$env\",role=\"vm-storage\",instance=~\"$instance\",container_ip=~\"$container_ip\",container_name=~\"$container_name\"}[1m]))",
     "legendFormat": "vm_tcplistener_write_timeouts_total"
    }
   ]
  },
  {
   "title": "vm_tcplistener_written_bytes_total/s",
   "type": "timeseries",
   "description": "vm_tcplistener_written_bytes_total",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 57 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum by () (rate(vm_tcplistener_written_bytes_total{cluster=~\"$cluster\",region=~\"$region\",env=~\"$env\",role=\"vm-storage\",instance=~\"$instance\",container_ip=~\"$container_ip\",container_name=~\"$container_name\"}[1m]))",
     "legendFormat": "vm_tcplistener_written_bytes_total"
    }
   ]
  },
  {
   "title": "vm_vmselect_concurrent_requests_limit_reached_total/s",
   "type": "timeseries",
   "description": "vm_vmselect_concurrent_requests_limit_reached_total",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 57 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by () (rate(vm_vmselect_concurrent_requests_limit_reached_total{cluster=~\"$cluster\",region=~\"$region\",env=~\"$env\",role=\"vm-storage\",instance=~\"$instance\",container_ip=~\"$container_ip\",container_name=~\"$container_name\"}[1m]))",
     "legendFormat": "vm_vmselect_concurrent_requests_limit_reached_total"
    }
   ]
  },
  {
   "title": "vm_vmselect_concurrent_requests_limit_timeout_total/s",
   "type": "timeseries",
   "description": "vm_vmselect_concurrent_requests_limit_timeout_total",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 65 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by () (rate(vm_vmselect_concurrent_requests_limit_timeout_total{cluster=~\"$cluster\",region=~\"$region\",env=~\"$env\",role=\"vm-storage\",instance=~\"$instance\",container_ip=~\"$container_ip\",container_name=~\"$container_name\"}[1m]))",
     "legendFormat": "vm_vmselect_concurrent_requests_limit_timeout_total"
    }
   ]
  },
  {
   "title": "vm_vmselect_conn_errors_total/s",
   "type": "timeseries",
   "description": "vm_vmselect_conn_errors_total",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 65 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by () (rate(vm_vmselect_conn_errors_total{cluster=~\"$cluster\",region=~\"$region\",env=~\"$env\",role=\"vm-storage\",instance=~\"$instance\",container_ip=~\"$container_ip\",container_name=~\"$container_name\"}[1m]))",
     "legendFormat": "vm_vmselect_conn_errors_total"
    }
   ]
  },
  {
   "title": "vm_vmselect_metric_blocks_read_total/s",
   "type": "timeseries",
   "description": "vm_vmselect_metric_blocks_read_total",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 65 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by () (rate(vm_vmselect_metric_blocks_read_total{cluster=~\"$cluster\",region=~\"$region\",env=~\"$env\",role=\"vm-storage\",instance=~\"$instance\",container_ip=~\"$container_ip\",container_name=~\"$container_name\"}[1m]))",
     "legendFormat": "vm_vmselect_metric_blocks_read_total"
    }
   ]
  },
  {
   "title": "vm_vmselect_metric_rows_read_total/s",
   "type": "timeseries",
   "description": "vm_vmselect_metric_rows_read_total",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 65 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by () (rate(vm_vmselect_metric_rows_read_total{cluster=~\"$cluster\",region=~\"$region\",env=~\"$env\",role=\"vm-storage\",instance=~\"$instance\",container_ip=~\"$container_ip\",container_name=~\"$container_name\"}[1m]))",
     "legendFormat": "vm_vmselect_metric_rows_read_total"
    }
   ]
  },
  {
   "title": "vm_vmselect_rpc_requests_total/s",
   "type": "timeseries",
   "description": "vm_vmselect_rpc_requests_total",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 73 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by () (rate(vm_vmselect_rpc_requests_total{cluster=~\"$cluster\",region=~\"$region\",env=~\"$env\",role=\"vm-storage\",instance=~\"$instance\",container_ip=~\"$container_ip\",container_name=~\"$container_name\"}[1m]))",
     "legendFormat": "vm_vmselect_rpc_requests_total"
    }
   ]
  },
  {
   "title": "vm_blocks",
   "type": "timeseries",
   "description": "vm_blocks",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 73 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(vm_blocks{cluster=~\"$cluster\",region=~\"$region\",env=~\"$env\",role=\"vm-storage\",instance=~\"$instance\",container_ip=~\"$container_ip\",container_name=~\"$container_name\"})",
     "legendFormat": "vm_blocks"
    }
   ]
  },
  {
   "title": "vm_cache_chars_current",
   "type": "timeseries",
   "description": "vm_cache_chars_current",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 73 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(vm_cache_chars_current{cluster=~\"$cluster\",region=~\"$region\",env=~\"$env\",role=\"vm-storage\",instance=~\"$instance\",container_ip=~\"$container_ip\",container_name=~\"$container_name\"})",
     "legendFormat": "vm_cache_chars_current"
    }
   ]
  },
  {
   "title": "vm_object_references",
   "type": "timeseries",
   "description": "vm_object_references",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 73 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(vm_object_references{cluster=~\"$cluster\",region=~\"$region\",env=~\"$env\",role=\"vm-storage\",instance=~\"$instance\",container_ip=~\"$container_ip\",container_name=~\"$container_name\"})",
     "legendFormat": "vm_object_references"
    }
   ]
  },
  {
   "title": "vm_partition_references",
   "type": "timeseries",
   "description": "vm_partition_references",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 81 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(vm_partition_references{cluster=~\"$cluster\",region=~\"$region\",env=~\"$env\",role=\"vm-storage\",instance=~\"$instance\",container_ip=~\"$container_ip\",container_name=~\"$container_name\"})",
     "legendFormat": "vm_partition_references"
    }
   ]
  },
  {
   "title": "vm_rows",
   "type": "timeseries",
   "description": "vm_rows",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 81 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(vm_rows{cluster=~\"$cluster\",region=~\"$region\",env=~\"$env\",role=\"vm-storage\",instance=~\"$instance\",container_ip=~\"$container_ip\",container_name=~\"$container_name\"})",
     "legendFormat": "vm_rows"
    }
   ]
  },
  {
   "title": "vm_tcplistener_conns",
   "type": "timeseries",
   "description": "vm_tcplistener_conns",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 81 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(vm_tcplistener_conns{cluster=~\"$cluster\",region=~\"$region\",env=~\"$env\",role=\"vm-storage\",instance=~\"$instance\",container_ip=~\"$container_ip\",container_name=~\"$container_name\"})",
     "legendFormat": "vm_tcplistener_conns"
    }
   ]
  },
  {
   "title": "vm_vmselect_conns",
   "type": "timeseries",
   "description": "vm_vmselect_conns",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 81 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(vm_vmselect_conns{cluster=~\"$cluster\",region=~\"$region\",env=~\"$env\",role=\"vm-storage\",instance=~\"$instance\",container_ip=~\"$container_ip\",container_name=~\"$container_name\"})",
     "legendFormat": "vm_vmselect_conns"
    }
   ]
  },
  {
   "title": "vm_active_merges",
   "type": "timeseries",
   "description": "vm_active_merges",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 89 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(vm_active_merges{cluster=~\"$cluster\",region=~\"$region\",env=~\"$env\",role=\"vm-storage\",instance=~\"$instance\",container_ip=~\"$container_ip\",container_name=~\"$container_name\"})",
     "legendFormat": "vm_active_merges"
    }
   ]
  },
  {
   "title": "vm_cache_entries",
   "type": "timeseries",
   "description": "vm_cache_entries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 89 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(vm_cache_entries{cluster=~\"$cluster\",region=~\"$region\",env=~\"$env\",role=\"vm-storage\",instance=~\"$instance\",container_ip=~\"$container_ip\",container_name=~\"$container_name\"})",
     "legendFormat": "vm_cache_entries"
    }
   ]
  },
  {
   "title": "vm_part_references",
   "type": "timeseries",
   "description": "vm_part_references",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 89 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(vm_part_references{cluster=~\"$cluster\",region=~\"$region\",env=~\"$env\",role=\"vm-storage\",instance=~\"$instance\",container_ip=~\"$container_ip\",container_name=~\"$container_name\"})",
     "legendFormat": "vm_part_references"
    }
   ]
  },
  {
   "title": "vm_parts",
   "type": "timeseries",
   "description": "vm_parts",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 89 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(vm_parts{cluster=~\"$cluster\",region=~\"$region\",env=~\"$env\",role=\"vm-storage\",instance=~\"$instance\",container_ip=~\"$container_ip\",container_name=~\"$container_name\"})",
     "legendFormat": "vm_parts"
    }
   ]
  },
  {
   "title": "vm_pending_rows",
   "type": "timeseries",
   "description": "vm_pending_rows",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 97 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(vm_pending_rows{cluster=~\"$cluster\",region=~\"$region\",env=~\"$env\",role=\"vm-storage\",instance=~\"$instance\",container_ip=~\"$container_ip\",container_name=~\"$container_name\"})",
     "legendFormat": "vm_pending_rows"
    }
   ]
  },
  {
   "title": "vm_cache_size_bytes",
   "type": "timeseries",
   "description": "vm_cache_size_bytes",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 97 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum(vm_cache_size_bytes{cluster=~\"$cluster\",region=~\"$region\",env=~\"$env\",role=\"vm-storage\",instance=~\"$instance\",container_ip=~\"$container_ip\",container_name=~\"$container_name\"})",
     "legendFormat": "vm_cache_size_bytes"
    }
   ]
  },
  {
   "title": "vm_data_size_bytes",
   "type": "timeseries",
   "description": "vm_data_size_bytes",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 97 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum(vm_data_size_bytes{cluster=~\"$cluster\",region=~\"$region\",env=~\"$env\",role=\"vm-storage\",instance=~\"$instance\",container_ip=~\"$container_ip\",container_name=~\"$container_name\"})",
     "legendFormat": "vm_data_size_bytes"
    }
   ]
  },
  {
   "title": "vm_free_disk_space_bytes",
   "type": "timeseries",
   "description": "vm_free_disk_space_bytes",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 97 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum(vm_free_disk_space_bytes{cluster=~\"$cluster\",region=~\"$region\",env=~\"$env\",role=\"vm-storage\",instance=~\"$instance\",container_ip=~\"$container_ip\",container_name=~\"$container_name\"})",
     "legendFormat": "vm_free_disk_space_bytes"
    }
   ]
  },
  {
   "title": "vm_free_disk_space_limit_bytes",
   "type": "timeseries",
   "description": "vm_free_disk_space_limit_bytes",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 105 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum(vm_free_disk_space_limit_bytes{cluster=~\"$cluster\",region=~\"$region\",env=~\"$env\",role=\"vm-storage\",instance=~\"$instance\",container_ip=~\"$container_ip\",container_name=~\"$container_name\"})",
     "legendFormat": "vm_free_disk_space_limit_bytes"
    }
   ]
  },
  {
   "title": "vm_http_request_duration_seconds_bucket",
   "type": "heatmap",
   "description": "vm_http_request_duration_seconds_bucket",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 105 },
   "targets": [
    {
     "expr": "sum(increase(label_replace(vm_http_request_duration_seconds_bucket{cluster=~\"$cluster\",region=~\"$region\",env=~\"$env\",role=\"vm-storage\",instance=~\"$instance\",container_ip=~\"$container_ip\",container_name=~\"$container_name\"}, \"le\", \"$1\", \"vmrange\", \"([^\\\\n]+)\\\\.\\\\.\\\\.([^\\\\n]+)\")[1m])) by (le)",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "vm_index_search_duration_seconds_bucket",
   "type": "heatmap",
   "description": "vm_index_search_duration_seconds_bucket",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 105 },
   "targets": [
    {
     "expr": "sum(increase(label_replace(vm_index_search_duration_seconds_bucket{cluster=~\"$cluster\",region=~\"$region\",env=~\"$env\",role=\"vm-storage\",instance=~\"$instance\",container_ip=~\"$container_ip\",container_name=~\"$container_name\"}, \"le\", \"$1\", \"vmrange\", \"([^\\\\n]+)\\\\.\\\\.\\\\.([^\\\\n]+)\")[1m])) by (le)",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "vm_cache_chars_max",
   "type": "stat",
   "description": "vm_cache_chars_max",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 105 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(vm_cache_chars_max{instance=~\"$instance\",container_name=~\"$container_name\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "vm_storage_is_read_only",
   "type": "stat",
   "description": "vm_storage_is_read_only",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 113 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(vm_storage_is_read_only{instance=~\"$instance\",container_name=~\"$container_name\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "vm_cache_size_max_bytes",
   "type": "stat",
   "description": "vm_cache_size_max_bytes",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 113 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(vm_cache_size_max_bytes{instance=~\"$instance\",container_name=~\"$container_name\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "not added metrics", "type": "text", "gridPos": { "h": 8, "w": 6, "x": 6, "y": 113 }, "options": { "content": "* vm_app_version\n" } }
 ]
}