{
 "title": "golang process info - simple version",
 "description": "dashboard to show metrics who use https://github.com/VictoriaMetrics/metrics",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "ds", "label": "data source", "query": "prometheus" },
   {
    "name": "instance",
    "label": "instance",
    "query": {
     "query": "label_values(go_cpu_count,instance)"
    }
   },
   {
    "name": "container_name",
    "label": "Container Name",
    "query": {
     "query": "label_values(go_cpu_count,container_name)"
    }
   }
  ]
 },
 "panels": [
  { "title": "CPU", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "CPU time (system + user)",
   "type": "timeseries",
   "description": "process_cpu_seconds_total = process_cpu_seconds_system_total + \nprocess_cpu_seconds_user_total\n\nIf only 1 cpu core, max value is 100%; 2 cpu's max value is 200%.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "(sum by ()(rate(process_cpu_seconds_system_total{instance=~\"$instance\",container_name=~\"$container_name\"}[1m])))",
     "legendFormat": "process_cpu_seconds_system_total"
    },
    {
     "expr": "(sum by ()(rate(process_cpu_seconds_user_total{instance=~\"$instance\",container_name=~\"$container_name\"}[1m])))",
     "legendFormat": "process_cpu_seconds_user_total"
    }
   ]
  },
  {
   "title": "go_threads",
   "type": "timeseries",
   "description": "go_threads<br/>\ngo_goroutines<br/>\nprocess_num_threads<br/>",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "sum(go_threads{instance=~\"$instance\",container_name=~\"$container_name\"})",
     "legendFormat": "go_threads"
    },
    {
     "expr": "sum(go_goroutines{instance=~\"$instance\",container_name=~\"$container_name\"})",
     "legendFormat": "go_goroutines"
    },
    {
     "expr": "sum(process_num_threads{instance=~\"$instance\",container_name=~\"$container_name\"})",
     "legendFormat": "process_num_threads"
    }
   ]
  },
  {
   "title": "go_cgo_calls_count/s",
   "type": "timeseries",
   "description": "go_cgo_calls_count",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 1 },
   "targets": [
    {
     "expr": "sum by ()(rate(go_cgo_calls_count{instance=~\"$instance\",container_name=~\"$container_name\"}[1m]))",
     "legendFormat": "go_cgo_calls_count/s"
    }
   ]
  },
  { "title": "go memstats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "heap memorys - Stack view",
   "type": "timeseries",
   "description": "go_memstats_heap_inuse_bytes + go_memstats_heap_idle_bytes = go_memstats_heap_sys_bytes <br/>\n<br/>\ngo_memstats_heap_idle_bytes > go_memstats_heap_released_bytes",
   "gridPos": { "h": 12, "w": 6, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum(go_memstats_heap_inuse_bytes{instance=~\"$instance\",container_name=~\"$container_name\"})",
     "legendFormat": "heap_inuse"
    },
    {
     "expr": "sum(go_memstats_heap_idle_bytes{instance=~\"$instance\",container_name=~\"$container_name\"})",
     "legendFormat": "heap_idle"
    },
    {
     "expr": "sum(go_memstats_heap_released_bytes{instance=~\"$instance\",container_name=~\"$container_name\"})",
     "legendFormat": "released"
    }
   ]
  },
  {
   "title": "heap memorys - Stack view",
   "type": "timeseries",
   "description": "`go_memstats_heap_alloc_bytes / go_memstats_heap_inuse_bytes` should be as close to 100% as possible, otherwise it will prove that there is too much unused end part of each allocation",
   "gridPos": { "h": 12, "w": 6, "x": 6, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum(go_memstats_heap_alloc_bytes{instance=~\"$instance\",container_name=~\"$container_name\"})",
     "legendFormat": "go_memstats_heap_alloc_bytes"
    },
    {
     "expr": "sum(go_memstats_heap_inuse_bytes{instance=~\"$instance\",container_name=~\"$container_name\"})-sum(go_memstats_heap_alloc_bytes{instance=~\"$instance\",container_name=~\"$container_name\"})",
     "legendFormat": "Not use"
    }
   ]
  },
  {
   "title": "mcache memorys - Stack view",
   "type": "timeseries",
   "description": "go_memstats_mcache_sys_bytes include go_memstats_mcache_inuse_bytes",
   "gridPos": { "h": 12, "w": 6, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum(go_memstats_mcache_inuse_bytes{instance=~\"$instance\",container_name=~\"$container_name\"})",
     "legendFormat": "go_memstats_mcache_inuse_bytes"
    },
    {
     "expr": "sum(go_memstats_mcache_sys_bytes{instance=~\"$instance\",container_name=~\"$container_name\"})-sum(go_memstats_mcache_inuse_bytes{instance=~\"$instance\",container_name=~\"$container_name\"})",
     "legendFormat": "Not use"
    }
   ]
  },
  {
   "title": "mspan memorys - Stack view",
   "type": "timeseries",
   "description": "go_memstats_mspan_sys_bytes include go_memstats_mspan_inuse_bytes",
   "gridPos": { "h": 12, "w": 6, "x": 18, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum(go_memstats_mspan_inuse_bytes{instance=~\"$instance\",container_name=~\"$container_name\"})",
     "legendFormat": "go_memstats_mspan_inuse_bytes"
    },
    {
     "expr": "sum(go_memstats_mspan_sys_bytes{instance=~\"$instance\",container_name=~\"$container_name\"})-sum(go_memstats_mspan_inuse_bytes{instance=~\"$instance\",container_name=~\"$container_name\"})",
     "legendFormat": "Not use"
    }
   ]
  },
  {
   "title": "Memory type proportion",
   "type": "piechart",
   "description": "The sum of the seven types of memory values is exactly go_memstats_sys_bytes",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(go_memstats_other_sys_bytes{instance=~\"$instance\",container_name=~\"$container_name\"})",
     "legendFormat": "other_sys"
    },
    {
     "expr": "sum(go_memstats_buck_hash_sys_bytes{instance=~\"$instance\",container_name=~\"$container_name\"})",
     "legendFormat": "buck_hash_sys"
    },
    {
     "expr": "sum(go_memstats_gc_sys_bytes{instance=~\"$instance\",container_name=~\"$container_name\"})",
     "legendFormat": "gc_sys"
    },
    {
     "expr": "sum(go_memstats_mspan_sys_bytes{instance=~\"$instance\",container_name=~\"$container_name\"})",
     "legendFormat": "mspan_sys"
    },
    {
     "expr": "sum(go_memstats_mcache_sys_bytes{instance=~\"$instance\",container_name=~\"$container_name\"})",
     "legendFormat": "mcache"
    },
    {
     "expr": "sum(go_memstats_heap_inuse_bytes{instance=~\"$instance\",container_name=~\"$container_name\"})",
     "legendFormat": "heap_inuse"
    },
    {
     "expr": "sum(go_memstats_heap_idle_bytes{instance=~\"$instance\",container_name=~\"$container_name\"})",
     "legendFormat": "heap_idle"
    }
   ]
  },
  {
   "title": "go_memstats_heap_objects",
   "type": "timeseries",
   "description": "go_memstats_heap_objects<br/>\n\n`go_memstats_heap_alloc_bytes / go_memstats_heap_objects` will be the average size of object.",
   "gridPos": { "h": 12, "w": 3, "x": 12, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(go_memstats_heap_objects{instance=~\"$instance\",container_name=~\"$container_name\"})",
     "legendFormat": "heap_objects"
    }
   ]
  },
  {
   "title": "stack memorys - Stack view",
   "type": "timeseries",
   "description": "go_memstats_stack_sys_bytes include go_memstats_stack_inuse_bytes",
   "gridPos": { "h": 12, "w": 3, "x": 15, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum(go_memstats_stack_inuse_bytes{instance=~\"$instance\",container_name=~\"$container_name\"})",
     "legendFormat": "stack_inuse"
    },
    {
     "expr": "(sum(go_memstats_stack_sys_bytes{instance=~\"$instance\",container_name=~\"$container_name\"})-sum(go_memstats_stack_inuse_bytes{instance=~\"$instance\",container_name=~\"$container_name\"}))>0",
     "legendFormat": "Not use"
    }
   ]
  },
  {
   "title": "alloc_bytes",
   "type": "timeseries",
   "description": "go_memstats_alloc_bytes<br/>\ngo_memstats_alloc_bytes_total",
   "gridPos": { "h": 12, "w": 3, "x": 18, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum(go_memstats_alloc_bytes{instance=~\"$instance\",container_name=~\"$container_name\"})",
     "legendFormat": "current_alloc_bytes"
    },
    {
     "expr": "sum by ()(rate(go_memstats_alloc_bytes_total{instance=~\"$instance\",container_name=~\"$container_name\"}[1m]))",
     "legendFormat": "alloc_bytes/s"
    }
   ]
  },
  {
   "title": "memory operate times/s",
   "type": "timeseries",
   "description": "go_memstats_frees_total<br/>\ngo_memstats_lookups_total<br/>\ngo_memstats_mallocs_total<br/>",
   "gridPos": { "h": 12, "w": 3, "x": 21, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by ()(rate(go_memstats_frees_total{instance=~\"$instance\",container_name=~\"$container_name\"}[1m]))",
     "legendFormat": "go_memstats_frees_total"
    },
    {
     "expr": "sum by ()(rate(go_memstats_lookups_total{instance=~\"$instance\",container_name=~\"$container_name\"}[1m]))",
     "legendFormat": "go_memstats_lookups_total"
    },
    {
     "expr": "sum by ()(rate(go_memstats_mallocs_total{instance=~\"$instance\",container_name=~\"$container_name\"}[1m]))",
     "legendFormat": "go_memstats_mallocs_total"
    }
   ]
  },
  { "title": "GC", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 34 } },
  {
   "title": "go_gc_duration_seconds",
   "type": "heatmap",
   "description": "go_gc_duration_seconds<br/>\ngo_gc_duration_seconds_sum<br/>\ngo_gc_duration_seconds_count<br/>\n<br/>\nIn fact, I don’t understand how the `go_gc_duration_seconds` histogram reflects the behavior of gc. This chart only uses heatmap to represent the relationship between time, quantile and time consumption.\n",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 35 },
   "targets": [
    {
     "expr": "sum by (quantile)(increase(go_gc_duration_seconds{instance=~\"$instance\",container_name=~\"$container_name\"}[1m]))",
     "legendFormat": "{{quantile}}"
    }
   ]
  },
  {
   "title": "Average interval between GC",
   "type": "timeseries",
   "description": "go_memstats_last_gc_time_seconds is a unix timestamp.<br/>\ngo_memstats_next_gc_bytes<br/>\n<br/>\n\n`Average interval` shows the time interval between two gc.",
   "gridPos": { "h": 9, "w": 6, "x": 6, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "avg(increase(go_memstats_last_gc_time_seconds{instance=~\"$instance\",container_name=~\"$container_name\"}[1m])) >0",
     "legendFormat": "Average interval"
    },
    {
     "expr": "avg(go_memstats_next_gc_bytes{instance=~\"$instance\",container_name=~\"$container_name\"})",
     "legendFormat": "next_gc_bytes"
    }
   ]
  },
  {
   "title": "go_memstats_gc_cpu_fraction",
   "type": "timeseries",
   "description": "`go_memstats_gc_cpu_fraction` indicates the ratio of the CPU time occupied by the garbage collection process to the total CPU time of the program running. The smaller the better.",
   "gridPos": { "h": 9, "w": 6, "x": 12, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "max(go_memstats_gc_cpu_fraction{instance=~\"$instance\",container_name=~\"$container_name\"})",
     "legendFormat": "go_memstats_gc_cpu_fraction"
    }
   ]
  },
  {
   "title": "go_gc_forced_count",
   "type": "timeseries",
   "description": "go_gc_forced_count",
   "gridPos": { "h": 9, "w": 6, "x": 18, "y": 35 },
   "targets": [
    {
     "expr": "(sum by ()(rate(go_gc_forced_count{instance=~\"$instance\",container_name=~\"$container_name\"}[1m])))>0",
     "legendFormat": "go_gc_forced_count"
    }
   ]
  },
  { "title": "Process Memory", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 44 } },
  {
   "title": "Process resident memory",
   "type": "timeseries",
   "description": "process_resident_memory_bytes<br/>\nprocess_resident_memory_peak_bytes<br/>",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum(process_resident_memory_bytes{instance=~\"$instance\",container_name=~\"$container_name\"})",
     "legendFormat": "process_resident_memory"
    },
    {
     "expr": "sum(process_resident_memory_peak_bytes{instance=~\"$instance\",container_name=~\"$container_name\"})",
     "legendFormat": "resident_memory_peak"
    }
   ]
  },
  {
   "title": "Process resident memory - Stack view",
   "type": "timeseries",
   "description": "process_resident_memory_anon_bytes (Anonymous Memory)<br/>\nprocess_resident_memory_file_bytes<br/>\nprocess_resident_memory_shared_bytes<br/>",
   "gridPos": { "h": 9, "w": 6, "x": 6, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum(process_resident_memory_anon_bytes{instance=~\"$instance\",container_name=~\"$container_name\"})>0",
     "legendFormat": "Anonymous Memory"
    },
    {
     "expr": "sum(process_resident_memory_shared_bytes{instance=~\"$instance\",container_name=~\"$container_name\"})>0",
     "legendFormat": "resident_memory_shared"
    },
    {
     "expr": "sum(process_resident_memory_file_bytes{instance=~\"$instance\",container_name=~\"$container_name\"})>0",
     "legendFormat": "resident_memory_file"
    }
   ]
  },
  {
   "title": "Process virtual memory",
   "type": "timeseries",
   "description": "process_virtual_memory_bytes<br/>\nprocess_virtual_memory_peak_bytes",
   "gridPos": { "h": 9, "w": 6, "x": 12, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum(process_virtual_memory_bytes{instance=~\"$instance\",container_name=~\"$container_name\"})",
     "legendFormat": "process_virtual_memory"
    },
    {
     "expr": "sum(process_virtual_memory_peak_bytes{instance=~\"$instance\",container_name=~\"$container_name\"})",
     "legendFormat": "virtual_memory_peak"
    }
   ]
  },
  {
   "title": "process pagefaults / s",
   "type": "timeseries",
   "description": "process_minor_pagefaults_total<br/>\nprocess_major_pagefaults_total",
   "gridPos": { "h": 9, "w": 6, "x": 18, "y": 45 },
   "targets": [
    {
     "expr": "sum by ()(rate(process_minor_pagefaults_total{instance=~\"$instance\",container_name=~\"$container_name\"}[1m]))",
     "legendFormat": "process_minor_pagefaults"
    },
    {
     "expr": "sum by ()(rate(process_major_pagefaults_total{instance=~\"$instance\",container_name=~\"$container_name\"}[1m]))",
     "legendFormat": "process_major_pagefaults"
    }
   ]
  },
  { "title": "IO", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 54 } },
  {
   "title": "I/O per second",
   "type": "timeseries",
   "description": "process_io_read_bytes_total<br/>\nprocess_io_written_bytes_total<br/>\nprocess_io_storage_read_bytes_total<br/>\nprocess_io_storage_written_bytes_total<br/>\nprocess_io_read_syscalls_total<br/>\nprocess_io_write_syscalls_total",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 55 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum by ()(rate(process_io_read_bytes_total{instance=~\"$instance\",container_name=~\"$container_name\"}[1m]))",
     "legendFormat": "process_io_read_bytes_total"
    },
    {
     "expr": "sum by ()(rate(process_io_written_bytes_total{instance=~\"$instance\",container_name=~\"$container_name\"}[1m]))",
     "legendFormat": "process_io_written_bytes_total"
    },
    {
     "expr": "sum by ()(rate(process_io_storage_read_bytes_total{instance=~\"$instance\",container_name=~\"$container_name\"}[1m]))",
     "legendFormat": "process_io_storage_read_bytes_total"
    },
    {
     "expr": "sum by ()(rate(process_io_storage_written_bytes_total{instance=~\"$instance\",container_name=~\"$container_name\"}[1m]))",
     "legendFormat": "process_io_storage_written_bytes_total"
    },
    {
     "expr": "sum by ()(rate(process_io_read_syscalls_total{instance=~\"$instance\",container_name=~\"$container_name\"}[1m]))",
     "legendFormat": "read_syscalls/s"
    },
    {
     "expr": "sum by ()(rate(process_io_write_syscalls_total{instance=~\"$instance\",container_name=~\"$container_name\"}[1m]))",
     "legendFormat": "write_syscalls/s"
    }
   ]
  },
  { "title": "Stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 62 } },
  {
   "title": "go_cpu_count",
   "type": "stat",
   "description": "The go_cpu_count in some k8s environments is the number of cpu cores of the entire physical machine, not the number of cpu cores of the container.",
   "gridPos": { "h": 4, "w": 2, "x": 0, "y": 63 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(go_cpu_count{instance=~\"$instance\",container_name=~\"$container_name\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "go_gomaxprocs",
   "type": "stat",
   "description": "go_gomaxprocs<br/>\n\nThe value of the environment variable `GOMAXPROCS`.",
   "gridPos": { "h": 4, "w": 2, "x": 2, "y": 63 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(go_gomaxprocs{instance=~\"$instance\",container_name=~\"$container_name\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "process_start_time_seconds (min)",
   "type": "stat",
   "description": "process_start_time_seconds is a unix timestamp of process start.",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 63 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "time()-min(process_start_time_seconds{instance=~\"$instance\",container_name=~\"$container_name\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "from last_gc_time to now",
   "type": "stat",
   "description": "go_memstats_last_gc_time_seconds is a unix timestamp.<br/>",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 63 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "time()-max(go_memstats_last_gc_time_seconds{instance=~\"$instance\",container_name=~\"$container_name\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "next_gc_bytes (min)",
   "type": "stat",
   "description": "go_memstats_next_gc_bytes",
   "gridPos": { "h": 4, "w": 2, "x": 12, "y": 63 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "min(go_memstats_next_gc_bytes{instance=~\"$instance\",container_name=~\"$container_name\"})",
     "legendFormat": "min"
    }
   ]
  },
  {
   "title": "sys_bytes",
   "type": "stat",
   "description": "go_memstats_sys_bytes = <br/>\n\ngo_memstats_other_sys_bytes + go_memstats_buck_hash_sys_bytes + go_memstats_gc_sys_bytes + go_memstats_stack_sys_bytes + go_memstats_heap_idle_bytes + go_memstats_heap_inuse_bytes + go_memstats_mcache_sys_bytes + go_memstats_mspan_sys_bytes",
   "gridPos": { "h": 4, "w": 4, "x": 14, "y": 63 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(go_memstats_sys_bytes{instance=~\"$instance\",container_name=~\"$container_name\"})",
     "legendFormat": "sys_bytes"
    },
    {
     "expr": "sum(go_memstats_other_sys_bytes{instance=~\"$instance\",container_name=~\"$container_name\"})+sum(go_memstats_buck_hash_sys_bytes{instance=~\"$instance\",container_name=~\"$container_name\"})+sum(go_memstats_gc_sys_bytes{instance=~\"$instance\",container_name=~\"$container_name\"})+sum(go_memstats_stack_sys_bytes{instance=~\"$instance\",container_name=~\"$container_name\"})+sum(go_memstats_heap_idle_bytes{instance=~\"$instance\",container_name=~\"$container_name\"})+sum(go_memstats_heap_inuse_bytes{instance=~\"$instance\",container_name=~\"$container_name\"})+sum(go_memstats_mcache_sys_bytes{instance=~\"$instance\",container_name=~\"$container_name\"})+sum(go_memstats_mspan_sys_bytes{instance=~\"$instance\",container_name=~\"$container_name\"})",
     "legendFormat": "total"
    }
   ]
  },
  {
   "title": "go_info_ext",
   "type": "stat",
   "description": "go_info_ext",
   "gridPos": { "h": 4, "w": 4, "x": 18, "y": 63 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "go_info_ext{instance=~\"$instance\",container_name=~\"$container_name\"}",
     "legendFormat": "{{version}}"
    }
   ]
  },
  {
   "title": "go_version",
   "type": "stat",
   "description": "go_info",
   "gridPos": { "h": 4, "w": 2, "x": 22, "y": 63 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "go_info{instance=~\"$instance\",container_name=~\"$container_name\"}",
     "legendFormat": "{{version}}"
    }
   ]
  }
 ]
}