{
 "title": "vm-alert",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "ds", "label": "data source", "query": "prometheus" },
   { "name": "cluster", "label": "Cluster", "query": { "query": "label_values(flag, cluster)" } },
   {
    "name": "region",
    "label": "Region",
    "query": {
     "query": "label_values(flag{cluster=~\"$cluster\"}, region)"
    }
   },
   {
    "name": "env",
    "label": "Env",
    "query": {
     "query": "label_values(flag{cluster=~\"$cluster\",region=~\"$region\"}, env)"
    }
   },
   {
    "name": "instance",
    "label": "Instance",
    "query": {
     "query": "label_values(flag{cluster=~\"$cluster\",region=~\"$region\",env=~\"$env\",role=\"vm-alert\"}, instance)"
    }
   },
   {
    "name": "container_ip",
    "label": "Container IP",
    "query": {
     "query": "label_values(flag{cluster=~\"$cluster\",region=~\"$region\",env=~\"$env\",role=\"vm-alert\"}, container_ip)"
    }
   },
   {
    "name": "container_name",
    "label": "Container Name",
    "query": {
     "query": "label_values(flag{cluster=~\"$cluster\",region=~\"$region\",env=~\"$env\",role=\"vm-alert\"}, container_name)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "CPU time (system + user)",
   "type": "timeseries",
   "description": "process_cpu_seconds_total = process_cpu_seconds_system_total + \nprocess_cpu_seconds_user_total\n\nIf only 1 cpu core, max value is 100%; 2 cpu's max value is 200%.",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "(sum by ()(rate(process_cpu_seconds_system_total{cluster=~\"$cluster\",region=~\"$region\",env=~\"$env\",role=\"vm-alert\",instance=~\"$instance\",container_ip=~\"$container_ip\",container_name=~\"$container_name\"}[1m])))",
     "legendFormat": "process_cpu_seconds_system_total"
    },
    {
     "expr": "(sum by ()(rate(process_cpu_seconds_user_total{cluster=~\"$cluster\",region=~\"$region\",env=~\"$env\",role=\"vm-alert\",instance=~\"$instance\",container_ip=~\"$container_ip\",container_name=~\"$container_name\"}[1m])))",
     "legendFormat": "process_cpu_seconds_user_total"
    }
   ]
  },
  {
   "title": "metrics_push_bytes_pushed_total/s",
   "type": "timeseries",
   "description": "metrics_push_bytes_pushed_total",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by () (rate(metrics_push_bytes_pushed_total{cluster=~\"$cluster\",region=~\"$region\",env=~\"$env\",role=\"vm-alert\",instance=~\"$instance\",container_ip=~\"$container_ip\",container_name=~\"$container_name\"}[1m]))",
     "legendFormat": "metrics_push_bytes_pushed_total"
    }
   ]
  },
  {
   "title": "metrics_push_errors_total/s",
   "type": "timeseries",
   "description": "metrics_push_errors_total",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by () (rate(metrics_push_errors_total{cluster=~\"$cluster\",region=~\"$region\",env=~\"$env\",role=\"vm-alert\",instance=~\"$instance\",container_ip=~\"$container_ip\",container_name=~\"$container_name\"}[1m]))",
     "legendFormat": "metrics_push_errors_total"
    }
   ]
  },
  {
   "title": "metrics_push_total/s",
   "type": "timeseries",
   "description": "metrics_push_total",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by () (rate(metrics_push_total{cluster=~\"$cluster\",region=~\"$region\",env=~\"$env\",role=\"vm-alert\",instance=~\"$instance\",container_ip=~\"$container_ip\",container_name=~\"$container_name\"}[1m]))",
     "legendFormat": "metrics_push_total"
    }
   ]
  },
  {
   "title": "vm_cache_misses_total/s",
   "type": "timeseries",
   "description": "vm_cache_misses_total",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by () (rate(vm_cache_misses_total{cluster=~\"$cluster\",region=~\"$region\",env=~\"$env\",role=\"vm-alert\",instance=~\"$instance\",container_ip=~\"$container_ip\",container_name=~\"$container_name\"}[1m]))",
     "legendFormat": "vm_cache_misses_total"
    }
   ]
  },
  {
   "title": "vm_cache_requests_total/s",
   "type": "timeseries",
   "description": "vm_cache_requests_total",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by () (rate(vm_cache_requests_total{cluster=~\"$cluster\",region=~\"$region\",env=~\"$env\",role=\"vm-alert\",instance=~\"$instance\",container_ip=~\"$container_ip\",container_name=~\"$container_name\"}[1m]))",
     "legendFormat": "vm_cache_requests_total"
    }
   ]
  },
  {
   "title": "vm_http_request_errors_total/s",
   "type": "timeseries",
   "description": "vm_http_request_errors_total",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by () (rate(vm_http_request_errors_total{cluster=~\"$cluster\",region=~\"$region\",env=~\"$env\",role=\"vm-alert\",instance=~\"$instance\",container_ip=~\"$container_ip\",container_name=~\"$container_name\"}[1m]))",
     "legendFormat": "vm_http_request_errors_total"
    }
   ]
  },
  {
   "title": "vm_http_requests_total/s",
   "type": "timeseries",
   "description": "vm_http_requests_total",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by () (rate(vm_http_requests_total{cluster=~\"$cluster\",region=~\"$region\",env=~\"$env\",role=\"vm-alert\",instance=~\"$instance\",container_ip=~\"$container_ip\",container_name=~\"$container_name\"}[1m]))",
     "legendFormat": "vm_http_requests_total"
    }
   ]
  },
  {
   "title": "vm_log_messages_total/s",
   "type": "timeseries",
   "description": "vm_log_messages_total",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by () (rate(vm_log_messages_total{cluster=~\"$cluster\",region=~\"$region\",env=~\"$env\",role=\"vm-alert\",instance=~\"$instance\",container_ip=~\"$container_ip\",container_name=~\"$container_name\"}[1m]))",
     "legendFormat": "vm_log_messages_total"
    }
   ]
  },
  {
   "title": "vm_protoparser_rows_read_total/s",
   "type": "timeseries",
   "description": "vm_protoparser_rows_read_total",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by () (rate(vm_protoparser_rows_read_total{cluster=~\"$cluster\",region=~\"$region\",env=~\"$env\",role=\"vm-alert\",instance=~\"$instance\",container_ip=~\"$container_ip\",container_name=~\"$container_name\"}[1m]))",
     "legendFormat": "vm_protoparser_rows_read_total"
    }
   ]
  },
  {
   "title": "vm_rows_invalid_total/s",
   "type": "timeseries",
   "description": "vm_rows_invalid_total",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by () (rate(vm_rows_invalid_total{cluster=~\"$cluster\",region=~\"$region\",env=~\"$env\",role=\"vm-alert\",instance=~\"$instance\",container_ip=~\"$container_ip\",container_name=~\"$container_name\"}[1m]))",
     "legendFormat": "vm_rows_invalid_total"
    }
   ]
  },
  {
   "title": "vm_tcplistener_accepts_total/s",
   "type": "timeseries",
   "description": "vm_tcplistener_accepts_total",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by () (rate(vm_tcplistener_accepts_total{cluster=~\"$cluster\",region=~\"$region\",env=~\"$env\",role=\"vm-alert\",instance=~\"$instance\",container_ip=~\"$container_ip\",container_name=~\"$container_name\"}[1m]))",
     "legendFormat": "vm_tcplistener_accepts_total"
    }
   ]
  },
  {
   "title": "vm_tcplistener_errors_total/s",
   "type": "timeseries",
   "description": "vm_tcplistener_errors_total",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by () (rate(vm_tcplistener_errors_total{cluster=~\"$cluster\",region=~\"$region\",env=~\"$env\",role=\"vm-alert\",instance=~\"$instance\",container_ip=~\"$container_ip\",container_name=~\"$container_name\"}[1m]))",
     "legendFormat": "vm_tcplistener_errors_total"
    }
   ]
  },
  {
   "title": "vm_tcplistener_read_bytes_total/s",
   "type": "timeseries",
   "description": "vm_tcplistener_read_bytes_total",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum by () (rate(vm_tcplistener_read_bytes_total{cluster=~\"$cluster\",region=~\"$region\",env=~\"$env\",role=\"vm-alert\",instance=~\"$instance\",container_ip=~\"$container_ip\",container_name=~\"$container_name\"}[1m]))",
     "legendFormat": "vm_tcplistener_read_bytes_total"
    }
   ]
  },
  {
   "title": "vm_tcplistener_read_calls_total/s",
   "type": "timeseries",
   "description": "vm_tcplistener_read_calls_total",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by () (rate(vm_tcplistener_read_calls_total{cluster=~\"$cluster\",region=~\"$region\",env=~\"$env\",role=\"vm-alert\",instance=~\"$instance\",container_ip=~\"$container_ip\",container_name=~\"$container_name\"}[1m]))",
     "legendFormat": "vm_tcplistener_read_calls_total"
    }
   ]
  },
  {
   "title": "vm_tcplistener_read_timeouts_total/s",
   "type": "timeseries",
   "description": "vm_tcplistener_read_timeouts_total",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by () (rate(vm_tcplistener_read_timeouts_total{cluster=~\"$cluster\",region=~\"$region\",env=~\"$env\",role=\"vm-alert\",instance=~\"$instance\",container_ip=~\"$container_ip\",container_name=~\"$container_name\"}[1m]))",
     "legendFormat": "vm_tcplistener_read_timeouts_total"
    }
   ]
  },
  {
   "title": "vm_tcplistener_write_calls_total/s",
   "type": "timeseries",
   "description": "vm_tcplistener_write_calls_total",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by () (rate(vm_tcplistener_write_calls_total{cluster=~\"$cluster\",region=~\"$region\",env=~\"$env\",role=\"vm-alert\",instance=~\"$instance\",container_ip=~\"$container_ip\",container_name=~\"$container_name\"}[1m]))",
     "legendFormat": "vm_tcplistener_write_calls_total"
    }
   ]
  },
  {
   "title": "vm_tcplistener_write_timeouts_total/s",
   "type": "timeseries",
   "description": "vm_tcplistener_write_timeouts_total",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by () (rate(vm_tcplistener_write_timeouts_total{cluster=~\"$cluster\",region=~\"$region\",env=~\"$env\",role=\"vm-alert\",instance=~\"$instance\",container_ip=~\"$container_ip\",container_name=~\"$container_name\"}[1m]))",
     "legendFormat": "vm_tcplistener_write_timeouts_total"
    }
   ]
  },
  {
   "title": "vm_tcplistener_written_bytes_total/s",
   "type": "timeseries",
   "description": "vm_tcplistener_written_bytes_total",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum by () (rate(vm_tcplistener_written_bytes_total{cluster=~\"$cluster\",region=~\"$region\",env=~\"$env\",role=\"vm-alert\",instance=~\"$instance\",container_ip=~\"$container_ip\",container_name=~\"$container_name\"}[1m]))",
     "legendFormat": "vm_tcplistener_written_bytes_total"
    }
   ]
  },
  {
   "title": "vmalert_alerting_rules_errors_total/s",
   "type": "timeseries",
   "description": "vmalert_alerting_rules_errors_total",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by () (rate(vmalert_alerting_rules_errors_total{cluster=~\"$cluster\",region=~\"$region\",env=~\"$env\",role=\"vm-alert\",instance=~\"$instance\",container_ip=~\"$container_ip\",container_name=~\"$container_name\"}[1m]))",
     "legendFormat": "vmalert_alerting_rules_errors_total"
    }
   ]
  },
  {
   "title": "vmalert_alerts_send_errors_total/s",
   "type": "timeseries",
   "description": "vmalert_alerts_send_errors_total",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by () (rate(vmalert_alerts_send_errors_total{cluster=~\"$cluster\",region=~\"$region\",env=~\"$env\",role=\"vm-alert\",instance=~\"$instance\",container_ip=~\"$container_ip\",container_name=~\"$container_name\"}[1m]))",
     "legendFormat": "vmalert_alerts_send_errors_total"
    }
   ]
  },
  {
   "title": "vmalert_alerts_sent_total/s",
   "type": "timeseries",
   "description": "vmalert_alerts_sent_total",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by () (rate(vmalert_alerts_sent_total{cluster=~\"$cluster\",region=~\"$region\",env=~\"$env\",role=\"vm-alert\",instance=~\"$instance\",container_ip=~\"$container_ip\",container_name=~\"$container_name\"}[1m]))",
     "legendFormat": "vmalert_alerts_sent_total"
    }
   ]
  },
  {
   "title": "vmalert_iteration_missed_total/s",
   "type": "timeseries",
   "description": "vmalert_iteration_missed_total",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 49 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by () (rate(vmalert_iteration_missed_total{cluster=~\"$cluster\",region=~\"$region\",env=~\"$env\",role=\"vm-alert\",instance=~\"$instance\",container_ip=~\"$container_ip\",container_name=~\"$container_name\"}[1m]))",
     "legendFormat": "vmalert_iteration_missed_total"
    }
   ]
  },
  {
   "title": "vmalert_iteration_total/s",
   "type": "timeseries",
   "description": "vmalert_iteration_total",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 49 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by () (rate(vmalert_iteration_total{cluster=~\"$cluster\",region=~\"$region\",env=~\"$env\",role=\"vm-alert\",instance=~\"$instance\",container_ip=~\"$container_ip\",container_name=~\"$container_name\"}[1m]))",
     "legendFormat": "vmalert_iteration_total"
    }
   ]
  },
  {
   "title": "vm_cache_entries",
   "type": "timeseries",
   "description": "vm_cache_entries",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 49 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(vm_cache_entries{cluster=~\"$cluster\",region=~\"$region\",env=~\"$env\",role=\"vm-alert\",instance=~\"$instance\",container_ip=~\"$container_ip\",container_name=~\"$container_name\"})",
     "legendFormat": "vm_cache_entries"
    }
   ]
  },
  {
   "title": "vm_tcplistener_conns",
   "type": "timeseries",
   "description": "vm_tcplistener_conns",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 49 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(vm_tcplistener_conns{cluster=~\"$cluster\",region=~\"$region\",env=~\"$env\",role=\"vm-alert\",instance=~\"$instance\",container_ip=~\"$container_ip\",container_name=~\"$container_name\"})",
     "legendFormat": "vm_tcplistener_conns"
    }
   ]
  },
  {
   "title": "vmalert_alerting_rules_last_evaluation_samples",
   "type": "timeseries",
   "description": "vmalert_alerting_rules_last_evaluation_samples",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 57 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(vmalert_alerting_rules_last_evaluation_samples{cluster=~\"$cluster\",region=~\"$region\",env=~\"$env\",role=\"vm-alert\",instance=~\"$instance\",container_ip=~\"$container_ip\",container_name=~\"$container_name\"})",
     "legendFormat": "vmalert_alerting_rules_last_evaluation_samples"
    }
   ]
  },
  {
   "title": "vmalert_alerting_rules_last_evaluation_series_fetched",
   "type": "timeseries",
   "description": "vmalert_alerting_rules_last_evaluation_series_fetched",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 57 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(vmalert_alerting_rules_last_evaluation_series_fetched{cluster=~\"$cluster\",region=~\"$region\",env=~\"$env\",role=\"vm-alert\",instance=~\"$instance\",container_ip=~\"$container_ip\",container_name=~\"$container_name\"})",
     "legendFormat": "vmalert_alerting_rules_last_evaluation_series_fetched"
    }
   ]
  },
  {
   "title": "vmalert_alerts_firing",
   "type": "timeseries",
   "description": "vmalert_alerts_firing",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 57 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(vmalert_alerts_firing{cluster=~\"$cluster\",region=~\"$region\",env=~\"$env\",role=\"vm-alert\",instance=~\"$instance\",container_ip=~\"$container_ip\",container_name=~\"$container_name\"})",
     "legendFormat": "vmalert_alerts_firing"
    }
   ]
  },
  {
   "title": "vmalert_alerts_pending",
   "type": "timeseries",
   "description": "vmalert_alerts_pending",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 57 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(vmalert_alerts_pending{cluster=~\"$cluster\",region=~\"$region\",env=~\"$env\",role=\"vm-alert\",instance=~\"$instance\",container_ip=~\"$container_ip\",container_name=~\"$container_name\"})",
     "legendFormat": "vmalert_alerts_pending"
    }
   ]
  },
  {
   "title": "vmalert_iteration_duration_seconds",
   "type": "timeseries",
   "description": "vmalert_iteration_duration_seconds",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 65 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum(vmalert_iteration_duration_seconds{cluster=~\"$cluster\",region=~\"$region\",env=~\"$env\",role=\"vm-alert\",instance=~\"$instance\",container_ip=~\"$container_ip\",container_name=~\"$container_name\"})",
     "legendFormat": "vmalert_iteration_duration_seconds"
    }
   ]
  },
  {
   "title": "vm_cache_chars_current",
   "type": "timeseries",
   "description": "vm_cache_chars_current",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 65 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(vm_cache_chars_current{cluster=~\"$cluster\",region=~\"$region\",env=~\"$env\",role=\"vm-alert\",instance=~\"$instance\",container_ip=~\"$container_ip\",container_name=~\"$container_name\"})",
     "legendFormat": "vm_cache_chars_current"
    }
   ]
  },
  {
   "title": "metrics_push_interval_seconds",
   "type": "timeseries",
   "description": "metrics_push_interval_seconds",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 65 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum(metrics_push_interval_seconds{cluster=~\"$cluster\",region=~\"$region\",env=~\"$env\",role=\"vm-alert\",instance=~\"$instance\",container_ip=~\"$container_ip\",container_name=~\"$container_name\"})",
     "legendFormat": "metrics_push_interval_seconds"
    }
   ]
  },
  {
   "title": "metrics_push_block_size_bytes_bucket",
   "type": "heatmap",
   "description": "metrics_push_block_size_bytes_bucket",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 65 },
   "targets": [
    {
     "expr": "sum(increase(label_replace(metrics_push_block_size_bytes_bucket{cluster=~\"$cluster\",region=~\"$region\",env=~\"$env\",role=\"vm-alert\",instance=~\"$instance\",container_ip=~\"$container_ip\",container_name=~\"$container_name\"}, \"le\", \"$1\", \"vmrange\", \"([^\\\\n]+)\\\\.\\\\.\\\\.([^\\\\n]+)\")[1m])) by (le)",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "metrics_push_duration_seconds_bucket",
   "type": "heatmap",
   "description": "metrics_push_duration_seconds_bucket",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 73 },
   "targets": [
    {
     "expr": "sum(increase(label_replace(metrics_push_duration_seconds_bucket{cluster=~\"$cluster\",region=~\"$region\",env=~\"$env\",role=\"vm-alert\",instance=~\"$instance\",container_ip=~\"$container_ip\",container_name=~\"$container_name\"}, \"le\", \"$1\", \"vmrange\", \"([^\\\\n]+)\\\\.\\\\.\\\\.([^\\\\n]+)\")[1m])) by (le)",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "vmalert_remotewrite_flush_duration_seconds_bucket",
   "type": "heatmap",
   "description": "vmalert_remotewrite_flush_duration_seconds_bucket",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 73 },
   "targets": [
    {
     "expr": "sum(increase(label_replace(vmalert_remotewrite_flush_duration_seconds_bucket{cluster=~\"$cluster\",region=~\"$region\",env=~\"$env\",role=\"vm-alert\",instance=~\"$instance\",container_ip=~\"$container_ip\",container_name=~\"$container_name\"}, \"le\", \"$1\", \"vmrange\", \"([^\\\\n]+)\\\\.\\\\.\\\\.([^\\\\n]+)\")[1m])) by (le)",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "vm_cache_chars_max",
   "type": "stat",
   "description": "vm_cache_chars_max",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 73 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(vm_cache_chars_max{instance=~\"$instance\",container_name=~\"$container_name\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "vmalert_iteration_interval_seconds",
   "type": "stat",
   "description": "vmalert_iteration_interval_seconds",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 73 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(vmalert_iteration_interval_seconds{instance=~\"$instance\",container_name=~\"$container_name\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "not added metrics",
   "type": "text",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 81 },
   "options": {
    "content": "* vm_app_version\n* vmalert_iteration_duration_seconds_count\n* vmalert_iteration_duration_seconds_sum\n"
   }
  }
 ]
}