{
 "title": "vm-agent",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "ds", "label": "data source", "query": "prometheus" },
   { "name": "cluster", "label": "Cluster", "query": { "query": "label_values(flag, cluster)" } },
   {
    "name": "region",
    "label": "Region",
    "query": {
     "query": "label_values(flag{cluster=~\"$cluster\"}, region)"
    }
   },
   {
    "name": "env",
    "label": "Env",
    "query": {
     "query": "label_values(flag{cluster=~\"$cluster\",region=~\"$region\"}, env)"
    }
   },
   {
    "name": "instance",
    "label": "Instance",
    "query": {
     "query": "label_values(flag{cluster=~\"$cluster\",region=~\"$region\",env=~\"$env\",role=\"vm-agent\"}, instance)"
    }
   },
   {
    "name": "container_ip",
    "label": "Container IP",
    "query": {
     "query": "label_values(flag{cluster=~\"$cluster\",region=~\"$region\",env=~\"$env\",role=\"vm-agent\"}, container_ip)"
    }
   },
   {
    "name": "container_name",
    "label": "Container Name",
    "query": {
     "query": "label_values(flag{cluster=~\"$cluster\",region=~\"$region\",env=~\"$env\",role=\"vm-agent\"}, container_name)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "CPU time (system + user)",
   "type": "timeseries",
   "description": "process_cpu_seconds_total = process_cpu_seconds_system_total + \nprocess_cpu_seconds_user_total\n\nIf only 1 cpu core, max value is 100%; 2 cpu's max value is 200%.",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "(sum by ()(rate(process_cpu_seconds_system_total{cluster=~\"$cluster\",region=~\"$region\",env=~\"$env\",role=\"vm-agent\",instance=~\"$instance\",container_ip=~\"$container_ip\",container_name=~\"$container_name\"}[1m])))",
     "legendFormat": "process_cpu_seconds_system_total"
    },
    {
     "expr": "(sum by ()(rate(process_cpu_seconds_user_total{cluster=~\"$cluster\",region=~\"$region\",env=~\"$env\",role=\"vm-agent\",instance=~\"$instance\",container_ip=~\"$container_ip\",container_name=~\"$container_name\"}[1m])))",
     "legendFormat": "process_cpu_seconds_user_total"
    }
   ]
  },
  {
   "title": "metrics_push_bytes_pushed_total/s",
   "type": "timeseries",
   "description": "metrics_push_bytes_pushed_total",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by () (rate(metrics_push_bytes_pushed_total{cluster=~\"$cluster\",region=~\"$region\",env=~\"$env\",role=\"vm-agent\",instance=~\"$instance\",container_ip=~\"$container_ip\",container_name=~\"$container_name\"}[1m]))",
     "legendFormat": "metrics_push_bytes_pushed_total"
    }
   ]
  },
  {
   "title": "metrics_push_errors_total/s",
   "type": "timeseries",
   "description": "metrics_push_errors_total",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by () (rate(metrics_push_errors_total{cluster=~\"$cluster\",region=~\"$region\",env=~\"$env\",role=\"vm-agent\",instance=~\"$instance\",container_ip=~\"$container_ip\",container_name=~\"$container_name\"}[1m]))",
     "legendFormat": "metrics_push_errors_total"
    }
   ]
  },
  {
   "title": "metrics_push_total/s",
   "type": "timeseries",
   "description": "metrics_push_total",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by () (rate(metrics_push_total{cluster=~\"$cluster\",region=~\"$region\",env=~\"$env\",role=\"vm-agent\",instance=~\"$instance\",container_ip=~\"$container_ip\",container_name=~\"$container_name\"}[1m]))",
     "legendFormat": "metrics_push_total"
    }
   ]
  },
  {
   "title": "vm_cache_misses_total/s",
   "type": "timeseries",
   "description": "vm_cache_misses_total",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by () (rate(vm_cache_misses_total{cluster=~\"$cluster\",region=~\"$region\",env=~\"$env\",role=\"vm-agent\",instance=~\"$instance\",container_ip=~\"$container_ip\",container_name=~\"$container_name\"}[1m]))",
     "legendFormat": "vm_cache_misses_total"
    }
   ]
  },
  {
   "title": "vm_cache_requests_total/s",
   "type": "timeseries",
   "description": "vm_cache_requests_total",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by () (rate(vm_cache_requests_total{cluster=~\"$cluster\",region=~\"$region\",env=~\"$env\",role=\"vm-agent\",instance=~\"$instance\",container_ip=~\"$container_ip\",container_name=~\"$container_name\"}[1m]))",
     "legendFormat": "vm_cache_requests_total"
    }
   ]
  },
  {
   "title": "vm_http_request_errors_total/s",
   "type": "timeseries",
   "description": "vm_http_request_errors_total",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by () (rate(vm_http_request_errors_total{cluster=~\"$cluster\",region=~\"$region\",env=~\"$env\",role=\"vm-agent\",instance=~\"$instance\",container_ip=~\"$container_ip\",container_name=~\"$container_name\"}[1m]))",
     "legendFormat": "vm_http_request_errors_total"
    }
   ]
  },
  {
   "title": "vm_http_requests_total/s",
   "type": "timeseries",
   "description": "vm_http_requests_total",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by () (rate(vm_http_requests_total{cluster=~\"$cluster\",region=~\"$region\",env=~\"$env\",role=\"vm-agent\",instance=~\"$instance\",container_ip=~\"$container_ip\",container_name=~\"$container_name\"}[1m]))",
     "legendFormat": "vm_http_requests_total"
    }
   ]
  },
  {
   "title": "vm_ingestserver_request_errors_total/s",
   "type": "timeseries",
   "description": "vm_ingestserver_request_errors_total",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by () (rate(vm_ingestserver_request_errors_total{cluster=~\"$cluster\",region=~\"$region\",env=~\"$env\",role=\"vm-agent\",instance=~\"$instance\",container_ip=~\"$container_ip\",container_name=~\"$container_name\"}[1m]))",
     "legendFormat": "vm_ingestserver_request_errors_total"
    }
   ]
  },
  {
   "title": "vm_ingestserver_requests_total/s",
   "type": "timeseries",
   "description": "vm_ingestserver_requests_total",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by () (rate(vm_ingestserver_requests_total{cluster=~\"$cluster\",region=~\"$region\",env=~\"$env\",role=\"vm-agent\",instance=~\"$instance\",container_ip=~\"$container_ip\",container_name=~\"$container_name\"}[1m]))",
     "legendFormat": "vm_ingestserver_requests_total"
    }
   ]
  },
  {
   "title": "vm_log_messages_total/s",
   "type": "timeseries",
   "description": "vm_log_messages_total",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by () (rate(vm_log_messages_total{cluster=~\"$cluster\",region=~\"$region\",env=~\"$env\",role=\"vm-agent\",instance=~\"$instance\",container_ip=~\"$container_ip\",container_name=~\"$container_name\"}[1m]))",
     "legendFormat": "vm_log_messages_total"
    }
   ]
  },
  {
   "title": "vm_persistentqueue_blocks_dropped_total/s",
   "type": "timeseries",
   "description": "vm_persistentqueue_blocks_dropped_total",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by () (rate(vm_persistentqueue_blocks_dropped_total{cluster=~\"$cluster\",region=~\"$region\",env=~\"$env\",role=\"vm-agent\",instance=~\"$instance\",container_ip=~\"$container_ip\",container_name=~\"$container_name\"}[1m]))",
     "legendFormat": "vm_persistentqueue_blocks_dropped_total"
    }
   ]
  },
  {
   "title": "vm_persistentqueue_blocks_read_total/s",
   "type": "timeseries",
   "description": "vm_persistentqueue_blocks_read_total",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by () (rate(vm_persistentqueue_blocks_read_total{cluster=~\"$cluster\",region=~\"$region\",env=~\"$env\",role=\"vm-agent\",instance=~\"$instance\",container_ip=~\"$container_ip\",container_name=~\"$container_name\"}[1m]))",
     "legendFormat": "vm_persistentqueue_blocks_read_total"
    }
   ]
  },
  {
   "title": "vm_persistentqueue_blocks_written_total/s",
   "type": "timeseries",
   "description": "vm_persistentqueue_blocks_written_total",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by () (rate(vm_persistentqueue_blocks_written_total{cluster=~\"$cluster\",region=~\"$region\",env=~\"$env\",role=\"vm-agent\",instance=~\"$instance\",container_ip=~\"$container_ip\",container_name=~\"$container_name\"}[1m]))",
     "legendFormat": "vm_persistentqueue_blocks_written_total"
    }
   ]
  },
  {
   "title": "vm_persistentqueue_bytes_dropped_total/s",
   "type": "timeseries",
   "description": "vm_persistentqueue_bytes_dropped_total",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by () (rate(vm_persistentqueue_bytes_dropped_total{cluster=~\"$cluster\",region=~\"$region\",env=~\"$env\",role=\"vm-agent\",instance=~\"$instance\",container_ip=~\"$container_ip\",container_name=~\"$container_name\"}[1m]))",
     "legendFormat": "vm_persistentqueue_bytes_dropped_total"
    }
   ]
  },
  {
   "title": "vm_persistentqueue_bytes_read_total/s",
   "type": "timeseries",
   "description": "vm_persistentqueue_bytes_read_total",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by () (rate(vm_persistentqueue_bytes_read_total{cluster=~\"$cluster\",region=~\"$region\",env=~\"$env\",role=\"vm-agent\",instance=~\"$instance\",container_ip=~\"$container_ip\",container_name=~\"$container_name\"}[1m]))",
     "legendFormat": "vm_persistentqueue_bytes_read_total"
    }
   ]
  },
  {
   "title": "vm_persistentqueue_bytes_written_total/s",
   "type": "timeseries",
   "description": "vm_persistentqueue_bytes_written_total",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by () (rate(vm_persistentqueue_bytes_written_total{cluster=~\"$cluster\",region=~\"$region\",env=~\"$env\",role=\"vm-agent\",instance=~\"$instance\",container_ip=~\"$container_ip\",container_name=~\"$container_name\"}[1m]))",
     "legendFormat": "vm_persistentqueue_bytes_written_total"
    }
   ]
  },
  {
   "title": "vm_promscrape_config_changes_total/s",
   "type": "timeseries",
   "description": "vm_promscrape_config_changes_total",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by () (rate(vm_promscrape_config_changes_total{cluster=~\"$cluster\",region=~\"$region\",env=~\"$env\",role=\"vm-agent\",instance=~\"$instance\",container_ip=~\"$container_ip\",container_name=~\"$container_name\"}[1m]))",
     "legendFormat": "vm_promscrape_config_changes_total"
    }
   ]
  },
  {
   "title": "vm_promscrape_scrapers_started_total/s",
   "type": "timeseries",
   "description": "vm_promscrape_scrapers_started_total",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by () (rate(vm_promscrape_scrapers_started_total{cluster=~\"$cluster\",region=~\"$region\",env=~\"$env\",role=\"vm-agent\",instance=~\"$instance\",container_ip=~\"$container_ip\",container_name=~\"$container_name\"}[1m]))",
     "legendFormat": "vm_promscrape_scrapers_started_total"
    }
   ]
  },
  {
   "title": "vm_promscrape_scrapers_stopped_total/s",
   "type": "timeseries",
   "description": "vm_promscrape_scrapers_stopped_total",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by () (rate(vm_promscrape_scrapers_stopped_total{cluster=~\"$cluster\",region=~\"$region\",env=~\"$env\",role=\"vm-agent\",instance=~\"$instance\",container_ip=~\"$container_ip\",container_name=~\"$container_name\"}[1m]))",
     "legendFormat": "vm_promscrape_scrapers_stopped_total"
    }
   ]
  },
  {
   "title": "vm_promscrape_scrapes_total/s",
   "type": "timeseries",
   "description": "vm_promscrape_scrapes_total",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by () (rate(vm_promscrape_scrapes_total{cluster=~\"$cluster\",region=~\"$region\",env=~\"$env\",role=\"vm-agent\",instance=~\"$instance\",container_ip=~\"$container_ip\",container_name=~\"$container_name\"}[1m]))",
     "legendFormat": "vm_promscrape_scrapes_total"
    }
   ]
  },
  {
   "title": "vm_protoparser_blocks_read_total/s",
   "type": "timeseries",
   "description": "vm_protoparser_blocks_read_total",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by () (rate(vm_protoparser_blocks_read_total{cluster=~\"$cluster\",region=~\"$region\",env=~\"$env\",role=\"vm-agent\",instance=~\"$instance\",container_ip=~\"$container_ip\",container_name=~\"$container_name\"}[1m]))",
     "legendFormat": "vm_protoparser_blocks_read_total"
    }
   ]
  },
  {
   "title": "vm_protoparser_parse_errors_total/s",
   "type": "timeseries",
   "description": "vm_protoparser_parse_errors_total",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 49 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by () (rate(vm_protoparser_parse_errors_total{cluster=~\"$cluster\",region=~\"$region\",env=~\"$env\",role=\"vm-agent\",instance=~\"$instance\",container_ip=~\"$container_ip\",container_name=~\"$container_name\"}[1m]))",
     "legendFormat": "vm_protoparser_parse_errors_total"
    }
   ]
  },
  {
   "title": "vm_protoparser_process_errors_total/s",
   "type": "timeseries",
   "description": "vm_protoparser_process_errors_total",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 49 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by () (rate(vm_protoparser_process_errors_total{cluster=~\"$cluster\",region=~\"$region\",env=~\"$env\",role=\"vm-agent\",instance=~\"$instance\",container_ip=~\"$container_ip\",container_name=~\"$container_name\"}[1m]))",
     "legendFormat": "vm_protoparser_process_errors_total"
    }
   ]
  },
  {
   "title": "vm_protoparser_read_calls_total/s",
   "type": "timeseries",
   "description": "vm_protoparser_read_calls_total",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 49 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by () (rate(vm_protoparser_read_calls_total{cluster=~\"$cluster\",region=~\"$region\",env=~\"$env\",role=\"vm-agent\",instance=~\"$instance\",container_ip=~\"$container_ip\",container_name=~\"$container_name\"}[1m]))",
     "legendFormat": "vm_protoparser_read_calls_total"
    }
   ]
  },
  {
   "title": "vm_protoparser_read_errors_total/s",
   "type": "timeseries",
   "description": "vm_protoparser_read_errors_total",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 49 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by () (rate(vm_protoparser_read_errors_total{cluster=~\"$cluster\",region=~\"$region\",env=~\"$env\",role=\"vm-agent\",instance=~\"$instance\",container_ip=~\"$container_ip\",container_name=~\"$container_name\"}[1m]))",
     "legendFormat": "vm_protoparser_read_errors_total"
    }
   ]
  },
  {
   "title": "vm_protoparser_rows_dropped_total/s",
   "type": "timeseries",
   "description": "vm_protoparser_rows_dropped_total",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 57 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by () (rate(vm_protoparser_rows_dropped_total{cluster=~\"$cluster\",region=~\"$region\",env=~\"$env\",role=\"vm-agent\",instance=~\"$instance\",container_ip=~\"$container_ip\",container_name=~\"$container_name\"}[1m]))",
     "legendFormat": "vm_protoparser_rows_dropped_total"
    }
   ]
  },
  {
   "title": "vm_protoparser_rows_read_total/s",
   "type": "timeseries",
   "description": "vm_protoparser_rows_read_total",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 57 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by () (rate(vm_protoparser_rows_read_total{cluster=~\"$cluster\",region=~\"$region\",env=~\"$env\",role=\"vm-agent\",instance=~\"$instance\",container_ip=~\"$container_ip\",container_name=~\"$container_name\"}[1m]))",
     "legendFormat": "vm_protoparser_rows_read_total"
    }
   ]
  },
  {
   "title": "vm_protoparser_unmarshal_errors_total/s",
   "type": "timeseries",
   "description": "vm_protoparser_unmarshal_errors_total",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 57 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by () (rate(vm_protoparser_unmarshal_errors_total{cluster=~\"$cluster\",region=~\"$region\",env=~\"$env\",role=\"vm-agent\",instance=~\"$instance\",container_ip=~\"$container_ip\",container_name=~\"$container_name\"}[1m]))",
     "legendFormat": "vm_protoparser_unmarshal_errors_total"
    }
   ]
  },
  {
   "title": "vm_rows_invalid_total/s",
   "type": "timeseries",
   "description": "vm_rows_invalid_total",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 57 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by () (rate(vm_rows_invalid_total{cluster=~\"$cluster\",region=~\"$region\",env=~\"$env\",role=\"vm-agent\",instance=~\"$instance\",container_ip=~\"$container_ip\",container_name=~\"$container_name\"}[1m]))",
     "legendFormat": "vm_rows_invalid_total"
    }
   ]
  },
  {
   "title": "vm_tcplistener_accepts_total/s",
   "type": "timeseries",
   "description": "vm_tcplistener_accepts_total",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 65 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by () (rate(vm_tcplistener_accepts_total{cluster=~\"$cluster\",region=~\"$region\",env=~\"$env\",role=\"vm-agent\",instance=~\"$instance\",container_ip=~\"$container_ip\",container_name=~\"$container_name\"}[1m]))",
     "legendFormat": "vm_tcplistener_accepts_total"
    }
   ]
  },
  {
   "title": "vm_tcplistener_errors_total/s",
   "type": "timeseries",
   "description": "vm_tcplistener_errors_total",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 65 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by () (rate(vm_tcplistener_errors_total{cluster=~\"$cluster\",region=~\"$region\",env=~\"$env\",role=\"vm-agent\",instance=~\"$instance\",container_ip=~\"$container_ip\",container_name=~\"$container_name\"}[1m]))",
     "legendFormat": "vm_tcplistener_errors_total"
    }
   ]
  },
  {
   "title": "vm_tcplistener_read_bytes_total/s",
   "type": "timeseries",
   "description": "vm_tcplistener_read_bytes_total",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 65 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum by () (rate(vm_tcplistener_read_bytes_total{cluster=~\"$cluster\",region=~\"$region\",env=~\"$env\",role=\"vm-agent\",instance=~\"$instance\",container_ip=~\"$container_ip\",container_name=~\"$container_name\"}[1m]))",
     "legendFormat": "vm_tcplistener_read_bytes_total"
    }
   ]
  },
  {
   "title": "vm_tcplistener_read_calls_total/s",
   "type": "timeseries",
   "description": "vm_tcplistener_read_calls_total",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 65 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by () (rate(vm_tcplistener_read_calls_total{cluster=~\"$cluster\",region=~\"$region\",env=~\"$env\",role=\"vm-agent\",instance=~\"$instance\",container_ip=~\"$container_ip\",container_name=~\"$container_name\"}[1m]))",
     "legendFormat": "vm_tcplistener_read_calls_total"
    }
   ]
  },
  {
   "title": "vm_tcplistener_read_timeouts_total/s",
   "type": "timeseries",
   "description": "vm_tcplistener_read_timeouts_total",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 73 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by () (rate(vm_tcplistener_read_timeouts_total{cluster=~\"$cluster\",region=~\"$region\",env=~\"$env\",role=\"vm-agent\",instance=~\"$instance\",container_ip=~\"$container_ip\",container_name=~\"$container_name\"}[1m]))",
     "legendFormat": "vm_tcplistener_read_timeouts_total"
    }
   ]
  },
  {
   "title": "vm_tcplistener_write_calls_total/s",
   "type": "timeseries",
   "description": "vm_tcplistener_write_calls_total",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 73 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by () (rate(vm_tcplistener_write_calls_total{cluster=~\"$cluster\",region=~\"$region\",env=~\"$env\",role=\"vm-agent\",instance=~\"$instance\",container_ip=~\"$container_ip\",container_name=~\"$container_name\"}[1m]))",
     "legendFormat": "vm_tcplistener_write_calls_total"
    }
   ]
  },
  {
   "title": "vm_tcplistener_write_timeouts_total/s",
   "type": "timeseries",
   "description": "vm_tcplistener_write_timeouts_total",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 73 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by () (rate(vm_tcplistener_write_timeouts_total{cluster=~\"$cluster\",region=~\"$region\",env=~\"$env\",role=\"vm-agent\",instance=~\"$instance\",container_ip=~\"$container_ip\",container_name=~\"$container_name\"}[1m]))",
     "legendFormat": "vm_tcplistener_write_timeouts_total"
    }
   ]
  },
  {
   "title": "vm_tcplistener_written_bytes_total/s",
   "type": "timeseries",
   "description": "vm_tcplistener_written_bytes_total",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 73 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum by () (rate(vm_tcplistener_written_bytes_total{cluster=~\"$cluster\",region=~\"$region\",env=~\"$env\",role=\"vm-agent\",instance=~\"$instance\",container_ip=~\"$container_ip\",container_name=~\"$container_name\"}[1m]))",
     "legendFormat": "vm_tcplistener_written_bytes_total"
    }
   ]
  },
  {
   "title": "vmagent_http_request_errors_total/s",
   "type": "timeseries",
   "description": "vmagent_http_request_errors_total",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 81 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by () (rate(vmagent_http_request_errors_total{cluster=~\"$cluster\",region=~\"$region\",env=~\"$env\",role=\"vm-agent\",instance=~\"$instance\",container_ip=~\"$container_ip\",container_name=~\"$container_name\"}[1m]))",
     "legendFormat": "vmagent_http_request_errors_total"
    }
   ]
  },
  {
   "title": "vmagent_http_requests_total/s",
   "type": "timeseries",
   "description": "vmagent_http_requests_total",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 81 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by () (rate(vmagent_http_requests_total{cluster=~\"$cluster\",region=~\"$region\",env=~\"$env\",role=\"vm-agent\",instance=~\"$instance\",container_ip=~\"$container_ip\",container_name=~\"$container_name\"}[1m]))",
     "legendFormat": "vmagent_http_requests_total"
    }
   ]
  },
  {
   "title": "vmagent_remotewrite_blocks_sent_total/s",
   "type": "timeseries",
   "description": "vmagent_remotewrite_blocks_sent_total",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 81 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by () (rate(vmagent_remotewrite_blocks_sent_total{cluster=~\"$cluster\",region=~\"$region\",env=~\"$env\",role=\"vm-agent\",instance=~\"$instance\",container_ip=~\"$container_ip\",container_name=~\"$container_name\"}[1m]))",
     "legendFormat": "vmagent_remotewrite_blocks_sent_total"
    }
   ]
  },
  {
   "title": "vmagent_remotewrite_bytes_sent_total/s",
   "type": "timeseries",
   "description": "vmagent_remotewrite_bytes_sent_total",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 81 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by () (rate(vmagent_remotewrite_bytes_sent_total{cluster=~\"$cluster\",region=~\"$region\",env=~\"$env\",role=\"vm-agent\",instance=~\"$instance\",container_ip=~\"$container_ip\",container_name=~\"$container_name\"}[1m]))",
     "legendFormat": "vmagent_remotewrite_bytes_sent_total"
    }
   ]
  },
  {
   "title": "vmagent_remotewrite_errors_total/s",
   "type": "timeseries",
   "description": "vmagent_remotewrite_errors_total",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 89 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by () (rate(vmagent_remotewrite_errors_total{cluster=~\"$cluster\",region=~\"$region\",env=~\"$env\",role=\"vm-agent\",instance=~\"$instance\",container_ip=~\"$container_ip\",container_name=~\"$container_name\"}[1m]))",
     "legendFormat": "vmagent_remotewrite_errors_total"
    }
   ]
  },
  {
   "title": "vmagent_remotewrite_packets_dropped_total/s",
   "type": "timeseries",
   "description": "vmagent_remotewrite_packets_dropped_total",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 89 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by () (rate(vmagent_remotewrite_packets_dropped_total{cluster=~\"$cluster\",region=~\"$region\",env=~\"$env\",role=\"vm-agent\",instance=~\"$instance\",container_ip=~\"$container_ip\",container_name=~\"$container_name\"}[1m]))",
     "legendFormat": "vmagent_remotewrite_packets_dropped_total"
    }
   ]
  },
  {
   "title": "vmagent_remotewrite_rate_limit_reached_total/s",
   "type": "timeseries",
   "description": "vmagent_remotewrite_rate_limit_reached_total",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 89 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by () (rate(vmagent_remotewrite_rate_limit_reached_total{cluster=~\"$cluster\",region=~\"$region\",env=~\"$env\",role=\"vm-agent\",instance=~\"$instance\",container_ip=~\"$container_ip\",container_name=~\"$container_name\"}[1m]))",
     "legendFormat": "vmagent_remotewrite_rate_limit_reached_total"
    }
   ]
  },
  {
   "title": "vmagent_remotewrite_relabel_metrics_dropped_total/s",
   "type": "timeseries",
   "description": "vmagent_remotewrite_relabel_metrics_dropped_total",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 89 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by () (rate(vmagent_remotewrite_relabel_metrics_dropped_total{cluster=~\"$cluster\",region=~\"$region\",env=~\"$env\",role=\"vm-agent\",instance=~\"$instance\",container_ip=~\"$container_ip\",container_name=~\"$container_name\"}[1m]))",
     "legendFormat": "vmagent_remotewrite_relabel_metrics_dropped_total"
    }
   ]
  },
  {
   "title": "vmagent_remotewrite_requests_total/s",
   "type": "timeseries",
   "description": "vmagent_remotewrite_requests_total",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 97 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by () (rate(vmagent_remotewrite_requests_total{cluster=~\"$cluster\",region=~\"$region\",env=~\"$env\",role=\"vm-agent\",instance=~\"$instance\",container_ip=~\"$container_ip\",container_name=~\"$container_name\"}[1m]))",
     "legendFormat": "vmagent_remotewrite_requests_total"
    }
   ]
  },
  {
   "title": "vmagent_remotewrite_retries_count_total/s",
   "type": "timeseries",
   "description": "vmagent_remotewrite_retries_count_total",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 97 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by () (rate(vmagent_remotewrite_retries_count_total{cluster=~\"$cluster\",region=~\"$region\",env=~\"$env\",role=\"vm-agent\",instance=~\"$instance\",container_ip=~\"$container_ip\",container_name=~\"$container_name\"}[1m]))",
     "legendFormat": "vmagent_remotewrite_retries_count_total"
    }
   ]
  },
  {
   "title": "vmagent_remotewrite_rows_pushed_after_relabel_total/s",
   "type": "timeseries",
   "description": "vmagent_remotewrite_rows_pushed_after_relabel_total",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 97 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by () (rate(vmagent_remotewrite_rows_pushed_after_relabel_total{cluster=~\"$cluster\",region=~\"$region\",env=~\"$env\",role=\"vm-agent\",instance=~\"$instance\",container_ip=~\"$container_ip\",container_name=~\"$container_name\"}[1m]))",
     "legendFormat": "vmagent_remotewrite_rows_pushed_after_relabel_total"
    }
   ]
  },
  {
   "title": "vmagent_remotewrite_send_duration_seconds_total/s",
   "type": "timeseries",
   "description": "vmagent_remotewrite_send_duration_seconds_total",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 97 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum by () (rate(vmagent_remotewrite_send_duration_seconds_total{cluster=~\"$cluster\",region=~\"$region\",env=~\"$env\",role=\"vm-agent\",instance=~\"$instance\",container_ip=~\"$container_ip\",container_name=~\"$container_name\"}[1m]))",
     "legendFormat": "vmagent_remotewrite_send_duration_seconds_total"
    }
   ]
  },
  {
   "title": "vmagent_rows_inserted_total/s",
   "type": "timeseries",
   "description": "vmagent_rows_inserted_total",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 105 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by () (rate(vmagent_rows_inserted_total{cluster=~\"$cluster\",region=~\"$region\",env=~\"$env\",role=\"vm-agent\",instance=~\"$instance\",container_ip=~\"$container_ip\",container_name=~\"$container_name\"}[1m]))",
     "legendFormat": "vmagent_rows_inserted_total"
    }
   ]
  },
  {
   "title": "vmagent_remotewrite_queue_blocked",
   "type": "timeseries",
   "description": "vmagent_remotewrite_queue_blocked",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 105 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(vmagent_remotewrite_queue_blocked{cluster=~\"$cluster\",region=~\"$region\",env=~\"$env\",role=\"vm-agent\",instance=~\"$instance\",container_ip=~\"$container_ip\",container_name=~\"$container_name\"})",
     "legendFormat": "vmagent_remotewrite_queue_blocked"
    }
   ]
  },
  {
   "title": "vmagent_remotewrite_queues",
   "type": "timeseries",
   "description": "vmagent_remotewrite_queues",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 105 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(vmagent_remotewrite_queues{cluster=~\"$cluster\",region=~\"$region\",env=~\"$env\",role=\"vm-agent\",instance=~\"$instance\",container_ip=~\"$container_ip\",container_name=~\"$container_name\"})",
     "legendFormat": "vmagent_remotewrite_queues"
    }
   ]
  },
  {
   "title": "vm_cache_chars_current",
   "type": "timeseries",
   "description": "vm_cache_chars_current",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 105 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(vm_cache_chars_current{cluster=~\"$cluster\",region=~\"$region\",env=~\"$env\",role=\"vm-agent\",instance=~\"$instance\",container_ip=~\"$container_ip\",container_name=~\"$container_name\"})",
     "legendFormat": "vm_cache_chars_current"
    }
   ]
  },
  {
   "title": "vm_persistentqueue_bytes_pending",
   "type": "timeseries",
   "description": "vm_persistentqueue_bytes_pending",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 113 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(vm_persistentqueue_bytes_pending{cluster=~\"$cluster\",region=~\"$region\",env=~\"$env\",role=\"vm-agent\",instance=~\"$instance\",container_ip=~\"$container_ip\",container_name=~\"$container_name\"})",
     "legendFormat": "vm_persistentqueue_bytes_pending"
    }
   ]
  },
  {
   "title": "vm_promscrape_active_scrapers",
   "type": "timeseries",
   "description": "vm_promscrape_active_scrapers",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 113 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(vm_promscrape_active_scrapers{cluster=~\"$cluster\",region=~\"$region\",env=~\"$env\",role=\"vm-agent\",instance=~\"$instance\",container_ip=~\"$container_ip\",container_name=~\"$container_name\"})",
     "legendFormat": "vm_promscrape_active_scrapers"
    }
   ]
  },
  {
   "title": "vm_promscrape_scrape_pool_targets",
   "type": "timeseries",
   "description": "vm_promscrape_scrape_pool_targets",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 113 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(vm_promscrape_scrape_pool_targets{cluster=~\"$cluster\",region=~\"$region\",env=~\"$env\",role=\"vm-agent\",instance=~\"$instance\",container_ip=~\"$container_ip\",container_name=~\"$container_name\"})",
     "legendFormat": "vm_promscrape_scrape_pool_targets"
    }
   ]
  },
  {
   "title": "vm_tcplistener_conns",
   "type": "timeseries",
   "description": "vm_tcplistener_conns",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 113 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(vm_tcplistener_conns{cluster=~\"$cluster\",region=~\"$region\",env=~\"$env\",role=\"vm-agent\",instance=~\"$instance\",container_ip=~\"$container_ip\",container_name=~\"$container_name\"})",
     "legendFormat": "vm_tcplistener_conns"
    }
   ]
  },
  {
   "title": "vmagent_remotewrite_pending_inmemory_blocks",
   "type": "timeseries",
   "description": "vmagent_remotewrite_pending_inmemory_blocks",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 121 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(vmagent_remotewrite_pending_inmemory_blocks{cluster=~\"$cluster\",region=~\"$region\",env=~\"$env\",role=\"vm-agent\",instance=~\"$instance\",container_ip=~\"$container_ip\",container_name=~\"$container_name\"})",
     "legendFormat": "vmagent_remotewrite_pending_inmemory_blocks"
    }
   ]
  },
  {
   "title": "vm_cache_entries",
   "type": "timeseries",
   "description": "vm_cache_entries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 121 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(vm_cache_entries{cluster=~\"$cluster\",region=~\"$region\",env=~\"$env\",role=\"vm-agent\",instance=~\"$instance\",container_ip=~\"$container_ip\",container_name=~\"$container_name\"})",
     "legendFormat": "vm_cache_entries"
    }
   ]
  },
  {
   "title": "vm_promscrape_targets",
   "type": "timeseries",
   "description": "vm_promscrape_targets",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 121 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(vm_promscrape_targets{cluster=~\"$cluster\",region=~\"$region\",env=~\"$env\",role=\"vm-agent\",instance=~\"$instance\",container_ip=~\"$container_ip\",container_name=~\"$container_name\"})",
     "legendFormat": "vm_promscrape_targets"
    }
   ]
  },
  {
   "title": "vmagent_remotewrite_pending_data_bytes",
   "type": "timeseries",
   "description": "vmagent_remotewrite_pending_data_bytes",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 121 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum(vmagent_remotewrite_pending_data_bytes{cluster=~\"$cluster\",region=~\"$region\",env=~\"$env\",role=\"vm-agent\",instance=~\"$instance\",container_ip=~\"$container_ip\",container_name=~\"$container_name\"})",
     "legendFormat": "vmagent_remotewrite_pending_data_bytes"
    }
   ]
  },
  {
   "title": "metrics_push_block_size_bytes_bucket",
   "type": "heatmap",
   "description": "metrics_push_block_size_bytes_bucket",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 129 },
   "targets": [
    {
     "expr": "sum(increase(label_replace(metrics_push_block_size_bytes_bucket{cluster=~\"$cluster\",region=~\"$region\",env=~\"$env\",role=\"vm-agent\",instance=~\"$instance\",container_ip=~\"$container_ip\",container_name=~\"$container_name\"}, \"le\", \"$1\", \"vmrange\", \"([^\\\\n]+)\\\\.\\\\.\\\\.([^\\\\n]+)\")[1m])) by (le)",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "metrics_push_duration_seconds_bucket",
   "type": "heatmap",
   "description": "metrics_push_duration_seconds_bucket",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 129 },
   "targets": [
    {
     "expr": "sum(increase(label_replace(metrics_push_duration_seconds_bucket{cluster=~\"$cluster\",region=~\"$region\",env=~\"$env\",role=\"vm-agent\",instance=~\"$instance\",container_ip=~\"$container_ip\",container_name=~\"$container_name\"}, \"le\", \"$1\", \"vmrange\", \"([^\\\\n]+)\\\\.\\\\.\\\\.([^\\\\n]+)\")[1m])) by (le)",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "vm_promscrape_push_data_duration_seconds_bucket",
   "type": "heatmap",
   "description": "vm_promscrape_push_data_duration_seconds_bucket",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 129 },
   "targets": [
    {
     "expr": "sum(increase(label_replace(vm_promscrape_push_data_duration_seconds_bucket{cluster=~\"$cluster\",region=~\"$region\",env=~\"$env\",role=\"vm-agent\",instance=~\"$instance\",container_ip=~\"$container_ip\",container_name=~\"$container_name\"}, \"le\", \"$1\", \"vmrange\", \"([^\\\\n]+)\\\\.\\\\.\\\\.([^\\\\n]+)\")[1m])) by (le)",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "vm_promscrape_scrape_duration_seconds_bucket",
   "type": "heatmap",
   "description": "vm_promscrape_scrape_duration_seconds_bucket",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 129 },
   "targets": [
    {
     "expr": "sum(increase(label_replace(vm_promscrape_scrape_duration_seconds_bucket{cluster=~\"$cluster\",region=~\"$region\",env=~\"$env\",role=\"vm-agent\",instance=~\"$instance\",container_ip=~\"$container_ip\",container_name=~\"$container_name\"}, \"le\", \"$1\", \"vmrange\", \"([^\\\\n]+)\\\\.\\\\.\\\\.([^\\\\n]+)\")[1m])) by (le)",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "vm_promscrape_scrape_response_size_bytes_bucket",
   "type": "heatmap",
   "description": "vm_promscrape_scrape_response_size_bytes_bucket",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 137 },
   "targets": [
    {
     "expr": "sum(increase(label_replace(vm_promscrape_scrape_response_size_bytes_bucket{cluster=~\"$cluster\",region=~\"$region\",env=~\"$env\",role=\"vm-agent\",instance=~\"$instance\",container_ip=~\"$container_ip\",container_name=~\"$container_name\"}, \"le\", \"$1\", \"vmrange\", \"([^\\\\n]+)\\\\.\\\\.\\\\.([^\\\\n]+)\")[1m])) by (le)",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "vm_promscrape_scraped_samples_bucket",
   "type": "heatmap",
   "description": "vm_promscrape_scraped_samples_bucket",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 137 },
   "targets": [
    {
     "expr": "sum(increase(label_replace(vm_promscrape_scraped_samples_bucket{cluster=~\"$cluster\",region=~\"$region\",env=~\"$env\",role=\"vm-agent\",instance=~\"$instance\",container_ip=~\"$container_ip\",container_name=~\"$container_name\"}, \"le\", \"$1\", \"vmrange\", \"([^\\\\n]+)\\\\.\\\\.\\\\.([^\\\\n]+)\")[1m])) by (le)",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "vm_promscrape_service_discovery_duration_seconds_bucket",
   "type": "heatmap",
   "description": "vm_promscrape_service_discovery_duration_seconds_bucket",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 137 },
   "targets": [
    {
     "expr": "sum(increase(label_replace(vm_promscrape_service_discovery_duration_seconds_bucket{cluster=~\"$cluster\",region=~\"$region\",env=~\"$env\",role=\"vm-agent\",instance=~\"$instance\",container_ip=~\"$container_ip\",container_name=~\"$container_name\"}, \"le\", \"$1\", \"vmrange\", \"([^\\\\n]+)\\\\.\\\\.\\\\.([^\\\\n]+)\")[1m])) by (le)",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "vmagent_remotewrite_block_size_bytes_bucket",
   "type": "heatmap",
   "description": "vmagent_remotewrite_block_size_bytes_bucket",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 137 },
   "targets": [
    {
     "expr": "sum(increase(label_replace(vmagent_remotewrite_block_size_bytes_bucket{cluster=~\"$cluster\",region=~\"$region\",env=~\"$env\",role=\"vm-agent\",instance=~\"$instance\",container_ip=~\"$container_ip\",container_name=~\"$container_name\"}, \"le\", \"$1\", \"vmrange\", \"([^\\\\n]+)\\\\.\\\\.\\\\.([^\\\\n]+)\")[1m])) by (le)",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "vmagent_remotewrite_block_size_rows_bucket",
   "type": "heatmap",
   "description": "vmagent_remotewrite_block_size_rows_bucket",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 145 },
   "targets": [
    {
     "expr": "sum(increase(label_replace(vmagent_remotewrite_block_size_rows_bucket{cluster=~\"$cluster\",region=~\"$region\",env=~\"$env\",role=\"vm-agent\",instance=~\"$instance\",container_ip=~\"$container_ip\",container_name=~\"$container_name\"}, \"le\", \"$1\", \"vmrange\", \"([^\\\\n]+)\\\\.\\\\.\\\\.([^\\\\n]+)\")[1m])) by (le)",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "vmagent_remotewrite_duration_seconds_bucket",
   "type": "heatmap",
   "description": "vmagent_remotewrite_duration_seconds_bucket",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 145 },
   "targets": [
    {
     "expr": "sum(increase(label_replace(vmagent_remotewrite_duration_seconds_bucket{cluster=~\"$cluster\",region=~\"$region\",env=~\"$env\",role=\"vm-agent\",instance=~\"$instance\",container_ip=~\"$container_ip\",container_name=~\"$container_name\"}, \"le\", \"$1\", \"vmrange\", \"([^\\\\n]+)\\\\.\\\\.\\\\.([^\\\\n]+)\")[1m])) by (le)",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "metrics_push_interval_seconds",
   "type": "stat",
   "description": "metrics_push_interval_seconds",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 145 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(metrics_push_interval_seconds{instance=~\"$instance\",container_name=~\"$container_name\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "vm_cache_chars_max",
   "type": "stat",
   "description": "vm_cache_chars_max",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 145 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(vm_cache_chars_max{instance=~\"$instance\",container_name=~\"$container_name\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "vmagent_remotewrite_rate_limit",
   "type": "stat",
   "description": "vmagent_remotewrite_rate_limit",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 153 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(vmagent_remotewrite_rate_limit{instance=~\"$instance\",container_name=~\"$container_name\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "not added metrics", "type": "text", "gridPos": { "h": 8, "w": 6, "x": 0, "y": 153 }, "options": { "content": "* vm_app_version\n" } }
 ]
}