{
 "title": "vm-insert",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "ds", "label": "data source", "query": "prometheus" },
   { "name": "cluster", "label": "Cluster", "query": { "query": "label_values(flag, cluster)" } },
   {
    "name": "region",
    "label": "Region",
    "query": {
     "query": "label_values(flag{cluster=~\"$cluster\"}, region)"
    }
   },
   {
    "name": "env",
    "label": "Env",
    "query": {
     "query": "label_values(flag{cluster=~\"$cluster\",region=~\"$region\"}, env)"
    }
   },
   {
    "name": "instance",
    "label": "Instance",
    "query": {
     "query": "label_values(flag{cluster=~\"$cluster\",region=~\"$region\",env=~\"$env\",role=~\"vm-insert\"}, instance)"
    }
   },
   {
    "name": "container_ip",
    "label": "Container IP",
    "query": {
     "query": "label_values(flag{cluster=~\"$cluster\",region=~\"$region\",env=~\"$env\",role=~\"vm-insert\"}, container_ip)"
    }
   },
   {
    "name": "container_name",
    "label": "Container Name",
    "query": {
     "query": "label_values(flag{cluster=~\"$cluster\",region=~\"$region\",env=~\"$env\",role=~\"vm-insert\"}, container_name)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "CPU time (system + user)",
   "type": "timeseries",
   "description": "process_cpu_seconds_total = process_cpu_seconds_system_total + \nprocess_cpu_seconds_user_total\n\nIf only 1 cpu core, max value is 100%; 2 cpu's max value is 200%.",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "(sum by ()(rate(process_cpu_seconds_system_total{cluster=~\"$cluster\",region=~\"$region\",env=~\"$env\",role=\"vm-insert\",instance=~\"$instance\",container_ip=~\"$container_ip\",container_name=~\"$container_name\"}[1m])))",
     "legendFormat": "process_cpu_seconds_system_total"
    },
    {
     "expr": "(sum by ()(rate(process_cpu_seconds_user_total{cluster=~\"$cluster\",region=~\"$region\",env=~\"$env\",role=\"vm-insert\",instance=~\"$instance\",container_ip=~\"$container_ip\",container_name=~\"$container_name\"}[1m])))",
     "legendFormat": "process_cpu_seconds_user_total"
    }
   ]
  },
  {
   "title": "vm_cache_misses_total/s",
   "type": "timeseries",
   "description": "vm_cache_misses_total",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by () (rate(vm_cache_misses_total{cluster=~\"$cluster\",region=~\"$region\",env=~\"$env\",role=\"vm-insert\",instance=~\"$instance\",container_ip=~\"$container_ip\",container_name=~\"$container_name\"}[1m]))",
     "legendFormat": "vm_cache_misses_total"
    }
   ]
  },
  {
   "title": "vm_cache_requests_total/s",
   "type": "timeseries",
   "description": "vm_cache_requests_total",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by () (rate(vm_cache_requests_total{cluster=~\"$cluster\",region=~\"$region\",env=~\"$env\",role=\"vm-insert\",instance=~\"$instance\",container_ip=~\"$container_ip\",container_name=~\"$container_name\"}[1m]))",
     "legendFormat": "vm_cache_requests_total"
    }
   ]
  },
  {
   "title": "vm_http_request_errors_total/s",
   "type": "timeseries",
   "description": "vm_http_request_errors_total",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by () (rate(vm_http_request_errors_total{cluster=~\"$cluster\",region=~\"$region\",env=~\"$env\",role=\"vm-insert\",instance=~\"$instance\",container_ip=~\"$container_ip\",container_name=~\"$container_name\"}[1m]))",
     "legendFormat": "vm_http_request_errors_total"
    }
   ]
  },
  {
   "title": "vm_http_requests_total/s",
   "type": "timeseries",
   "description": "vm_http_requests_total",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by () (rate(vm_http_requests_total{cluster=~\"$cluster\",region=~\"$region\",env=~\"$env\",role=\"vm-insert\",instance=~\"$instance\",container_ip=~\"$container_ip\",container_name=~\"$container_name\"}[1m]))",
     "legendFormat": "vm_http_requests_total"
    }
   ]
  },
  {
   "title": "vm_ingestserver_request_errors_total/s",
   "type": "timeseries",
   "description": "vm_ingestserver_request_errors_total",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by () (rate(vm_ingestserver_request_errors_total{cluster=~\"$cluster\",region=~\"$region\",env=~\"$env\",role=\"vm-insert\",instance=~\"$instance\",container_ip=~\"$container_ip\",container_name=~\"$container_name\"}[1m]))",
     "legendFormat": "vm_ingestserver_request_errors_total"
    }
   ]
  },
  {
   "title": "vm_ingestserver_requests_total/s",
   "type": "timeseries",
   "description": "vm_ingestserver_requests_total",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by () (rate(vm_ingestserver_requests_total{cluster=~\"$cluster\",region=~\"$region\",env=~\"$env\",role=\"vm-insert\",instance=~\"$instance\",container_ip=~\"$container_ip\",container_name=~\"$container_name\"}[1m]))",
     "legendFormat": "vm_ingestserver_requests_total"
    }
   ]
  },
  {
   "title": "vm_log_messages_total/s",
   "type": "timeseries",
   "description": "vm_log_messages_total",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by () (rate(vm_log_messages_total{cluster=~\"$cluster\",region=~\"$region\",env=~\"$env\",role=\"vm-insert\",instance=~\"$instance\",container_ip=~\"$container_ip\",container_name=~\"$container_name\"}[1m]))",
     "legendFormat": "vm_log_messages_total"
    }
   ]
  },
  {
   "title": "vm_protoparser_blocks_read_total/s",
   "type": "timeseries",
   "description": "vm_protoparser_blocks_read_total",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by () (rate(vm_protoparser_blocks_read_total{cluster=~\"$cluster\",region=~\"$region\",env=~\"$env\",role=\"vm-insert\",instance=~\"$instance\",container_ip=~\"$container_ip\",container_name=~\"$container_name\"}[1m]))",
     "legendFormat": "vm_protoparser_blocks_read_total"
    }
   ]
  },
  {
   "title": "vm_protoparser_parse_errors_total/s",
   "type": "timeseries",
   "description": "vm_protoparser_parse_errors_total",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by () (rate(vm_protoparser_parse_errors_total{cluster=~\"$cluster\",region=~\"$region\",env=~\"$env\",role=\"vm-insert\",instance=~\"$instance\",container_ip=~\"$container_ip\",container_name=~\"$container_name\"}[1m]))",
     "legendFormat": "vm_protoparser_parse_errors_total"
    }
   ]
  },
  {
   "title": "vm_protoparser_process_errors_total/s",
   "type": "timeseries",
   "description": "vm_protoparser_process_errors_total",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by () (rate(vm_protoparser_process_errors_total{cluster=~\"$cluster\",region=~\"$region\",env=~\"$env\",role=\"vm-insert\",instance=~\"$instance\",container_ip=~\"$container_ip\",container_name=~\"$container_name\"}[1m]))",
     "legendFormat": "vm_protoparser_process_errors_total"
    }
   ]
  },
  {
   "title": "vm_protoparser_read_calls_total/s",
   "type": "timeseries",
   "description": "vm_protoparser_read_calls_total",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by () (rate(vm_protoparser_read_calls_total{cluster=~\"$cluster\",region=~\"$region\",env=~\"$env\",role=\"vm-insert\",instance=~\"$instance\",container_ip=~\"$container_ip\",container_name=~\"$container_name\"}[1m]))",
     "legendFormat": "vm_protoparser_read_calls_total"
    }
   ]
  },
  {
   "title": "vm_protoparser_read_errors_total/s",
   "type": "timeseries",
   "description": "vm_protoparser_read_errors_total",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by () (rate(vm_protoparser_read_errors_total{cluster=~\"$cluster\",region=~\"$region\",env=~\"$env\",role=\"vm-insert\",instance=~\"$instance\",container_ip=~\"$container_ip\",container_name=~\"$container_name\"}[1m]))",
     "legendFormat": "vm_protoparser_read_errors_total"
    }
   ]
  },
  {
   "title": "vm_protoparser_rows_dropped_total/s",
   "type": "timeseries",
   "description": "vm_protoparser_rows_dropped_total",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by () (rate(vm_protoparser_rows_dropped_total{cluster=~\"$cluster\",region=~\"$region\",env=~\"$env\",role=\"vm-insert\",instance=~\"$instance\",container_ip=~\"$container_ip\",container_name=~\"$container_name\"}[1m]))",
     "legendFormat": "vm_protoparser_rows_dropped_total"
    }
   ]
  },
  {
   "title": "vm_protoparser_rows_read_total/s",
   "type": "timeseries",
   "description": "vm_protoparser_rows_read_total",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by () (rate(vm_protoparser_rows_read_total{cluster=~\"$cluster\",region=~\"$region\",env=~\"$env\",role=\"vm-insert\",instance=~\"$instance\",container_ip=~\"$container_ip\",container_name=~\"$container_name\"}[1m]))",
     "legendFormat": "vm_protoparser_rows_read_total"
    }
   ]
  },
  {
   "title": "vm_protoparser_unmarshal_errors_total/s",
   "type": "timeseries",
   "description": "vm_protoparser_unmarshal_errors_total",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by () (rate(vm_protoparser_unmarshal_errors_total{cluster=~\"$cluster\",region=~\"$region\",env=~\"$env\",role=\"vm-insert\",instance=~\"$instance\",container_ip=~\"$container_ip\",container_name=~\"$container_name\"}[1m]))",
     "legendFormat": "vm_protoparser_unmarshal_errors_total"
    }
   ]
  },
  {
   "title": "vm_protoparser_write_errors_total/s",
   "type": "timeseries",
   "description": "vm_protoparser_write_errors_total",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by () (rate(vm_protoparser_write_errors_total{cluster=~\"$cluster\",region=~\"$region\",env=~\"$env\",role=\"vm-insert\",instance=~\"$instance\",container_ip=~\"$container_ip\",container_name=~\"$container_name\"}[1m]))",
     "legendFormat": "vm_protoparser_write_errors_total"
    }
   ]
  },
  {
   "title": "vm_rows_inserted_total/s",
   "type": "timeseries",
   "description": "vm_rows_inserted_total",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by () (rate(vm_rows_inserted_total{cluster=~\"$cluster\",region=~\"$region\",env=~\"$env\",role=\"vm-insert\",instance=~\"$instance\",container_ip=~\"$container_ip\",container_name=~\"$container_name\"}[1m]))",
     "legendFormat": "vm_rows_inserted_total"
    }
   ]
  },
  {
   "title": "vm_rows_invalid_total/s",
   "type": "timeseries",
   "description": "vm_rows_invalid_total",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by () (rate(vm_rows_invalid_total{cluster=~\"$cluster\",region=~\"$region\",env=~\"$env\",role=\"vm-insert\",instance=~\"$instance\",container_ip=~\"$container_ip\",container_name=~\"$container_name\"}[1m]))",
     "legendFormat": "vm_rows_invalid_total"
    }
   ]
  },
  {
   "title": "vm_rpc_connection_errors_total/s",
   "type": "timeseries",
   "description": "vm_rpc_connection_errors_total",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by () (rate(vm_rpc_connection_errors_total{cluster=~\"$cluster\",region=~\"$region\",env=~\"$env\",role=\"vm-insert\",instance=~\"$instance\",container_ip=~\"$container_ip\",container_name=~\"$container_name\"}[1m]))",
     "legendFormat": "vm_rpc_connection_errors_total"
    }
   ]
  },
  {
   "title": "vm_rpc_dial_errors_total/s",
   "type": "timeseries",
   "description": "vm_rpc_dial_errors_total",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by () (rate(vm_rpc_dial_errors_total{cluster=~\"$cluster\",region=~\"$region\",env=~\"$env\",role=\"vm-insert\",instance=~\"$instance\",container_ip=~\"$container_ip\",container_name=~\"$container_name\"}[1m]))",
     "legendFormat": "vm_rpc_dial_errors_total"
    }
   ]
  },
  {
   "title": "vm_rpc_handshake_errors_total/s",
   "type": "timeseries",
   "description": "vm_rpc_handshake_errors_total",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by () (rate(vm_rpc_handshake_errors_total{cluster=~\"$cluster\",region=~\"$region\",env=~\"$env\",role=\"vm-insert\",instance=~\"$instance\",container_ip=~\"$container_ip\",container_name=~\"$container_name\"}[1m]))",
     "legendFormat": "vm_rpc_handshake_errors_total"
    }
   ]
  },
  {
   "title": "vm_rpc_rerouted_rows_processed_total/s",
   "type": "timeseries",
   "description": "vm_rpc_rerouted_rows_processed_total",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 49 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by () (rate(vm_rpc_rerouted_rows_processed_total{cluster=~\"$cluster\",region=~\"$region\",env=~\"$env\",role=\"vm-insert\",instance=~\"$instance\",container_ip=~\"$container_ip\",container_name=~\"$container_name\"}[1m]))",
     "legendFormat": "vm_rpc_rerouted_rows_processed_total"
    }
   ]
  },
  {
   "title": "vm_rpc_reroutes_total/s",
   "type": "timeseries",
   "description": "vm_rpc_reroutes_total",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 49 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by () (rate(vm_rpc_reroutes_total{cluster=~\"$cluster\",region=~\"$region\",env=~\"$env\",role=\"vm-insert\",instance=~\"$instance\",container_ip=~\"$container_ip\",container_name=~\"$container_name\"}[1m]))",
     "legendFormat": "vm_rpc_reroutes_total"
    }
   ]
  },
  {
   "title": "vm_rpc_rows_dropped_on_overload_total/s",
   "type": "timeseries",
   "description": "vm_rpc_rows_dropped_on_overload_total",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 49 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by () (rate(vm_rpc_rows_dropped_on_overload_total{cluster=~\"$cluster\",region=~\"$region\",env=~\"$env\",role=\"vm-insert\",instance=~\"$instance\",container_ip=~\"$container_ip\",container_name=~\"$container_name\"}[1m]))",
     "legendFormat": "vm_rpc_rows_dropped_on_overload_total"
    }
   ]
  },
  {
   "title": "vm_rpc_rows_incompletely_replicated_total/s",
   "type": "timeseries",
   "description": "vm_rpc_rows_incompletely_replicated_total",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 49 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by () (rate(vm_rpc_rows_incompletely_replicated_total{cluster=~\"$cluster\",region=~\"$region\",env=~\"$env\",role=\"vm-insert\",instance=~\"$instance\",container_ip=~\"$container_ip\",container_name=~\"$container_name\"}[1m]))",
     "legendFormat": "vm_rpc_rows_incompletely_replicated_total"
    }
   ]
  },
  {
   "title": "vm_rpc_rows_pushed_total/s",
   "type": "timeseries",
   "description": "vm_rpc_rows_pushed_total",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 57 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by () (rate(vm_rpc_rows_pushed_total{cluster=~\"$cluster\",region=~\"$region\",env=~\"$env\",role=\"vm-insert\",instance=~\"$instance\",container_ip=~\"$container_ip\",container_name=~\"$container_name\"}[1m]))",
     "legendFormat": "vm_rpc_rows_pushed_total"
    }
   ]
  },
  {
   "title": "vm_rpc_rows_rerouted_from_here_total/s",
   "type": "timeseries",
   "description": "vm_rpc_rows_rerouted_from_here_total",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 57 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by () (rate(vm_rpc_rows_rerouted_from_here_total{cluster=~\"$cluster\",region=~\"$region\",env=~\"$env\",role=\"vm-insert\",instance=~\"$instance\",container_ip=~\"$container_ip\",container_name=~\"$container_name\"}[1m]))",
     "legendFormat": "vm_rpc_rows_rerouted_from_here_total"
    }
   ]
  },
  {
   "title": "vm_rpc_rows_rerouted_to_here_total/s",
   "type": "timeseries",
   "description": "vm_rpc_rows_rerouted_to_here_total",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 57 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by () (rate(vm_rpc_rows_rerouted_to_here_total{cluster=~\"$cluster\",region=~\"$region\",env=~\"$env\",role=\"vm-insert\",instance=~\"$instance\",container_ip=~\"$container_ip\",container_name=~\"$container_name\"}[1m]))",
     "legendFormat": "vm_rpc_rows_rerouted_to_here_total"
    }
   ]
  },
  {
   "title": "vm_rpc_rows_sent_total/s",
   "type": "timeseries",
   "description": "vm_rpc_rows_sent_total",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 57 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by () (rate(vm_rpc_rows_sent_total{cluster=~\"$cluster\",region=~\"$region\",env=~\"$env\",role=\"vm-insert\",instance=~\"$instance\",container_ip=~\"$container_ip\",container_name=~\"$container_name\"}[1m]))",
     "legendFormat": "vm_rpc_rows_sent_total"
    }
   ]
  },
  {
   "title": "vm_rpc_send_duration_seconds_total/s",
   "type": "timeseries",
   "description": "vm_rpc_send_duration_seconds_total",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 65 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum by () (rate(vm_rpc_send_duration_seconds_total{cluster=~\"$cluster\",region=~\"$region\",env=~\"$env\",role=\"vm-insert\",instance=~\"$instance\",container_ip=~\"$container_ip\",container_name=~\"$container_name\"}[1m]))",
     "legendFormat": "vm_rpc_send_duration_seconds_total"
    }
   ]
  },
  {
   "title": "vm_tcpdialer_dials_total/s",
   "type": "timeseries",
   "description": "vm_tcpdialer_dials_total",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 65 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by () (rate(vm_tcpdialer_dials_total{cluster=~\"$cluster\",region=~\"$region\",env=~\"$env\",role=\"vm-insert\",instance=~\"$instance\",container_ip=~\"$container_ip\",container_name=~\"$container_name\"}[1m]))",
     "legendFormat": "vm_tcpdialer_dials_total"
    }
   ]
  },
  {
   "title": "vm_tcpdialer_errors_total/s",
   "type": "timeseries",
   "description": "vm_tcpdialer_errors_total",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 65 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by () (rate(vm_tcpdialer_errors_total{cluster=~\"$cluster\",region=~\"$region\",env=~\"$env\",role=\"vm-insert\",instance=~\"$instance\",container_ip=~\"$container_ip\",container_name=~\"$container_name\"}[1m]))",
     "legendFormat": "vm_tcpdialer_errors_total"
    }
   ]
  },
  {
   "title": "vm_tcpdialer_read_bytes_total/s",
   "type": "timeseries",
   "description": "vm_tcpdialer_read_bytes_total",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 65 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum by () (rate(vm_tcpdialer_read_bytes_total{cluster=~\"$cluster\",region=~\"$region\",env=~\"$env\",role=\"vm-insert\",instance=~\"$instance\",container_ip=~\"$container_ip\",container_name=~\"$container_name\"}[1m]))",
     "legendFormat": "vm_tcpdialer_read_bytes_total"
    }
   ]
  },
  {
   "title": "vm_tcpdialer_read_calls_total/s",
   "type": "timeseries",
   "description": "vm_tcpdialer_read_calls_total",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 73 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by () (rate(vm_tcpdialer_read_calls_total{cluster=~\"$cluster\",region=~\"$region\",env=~\"$env\",role=\"vm-insert\",instance=~\"$instance\",container_ip=~\"$container_ip\",container_name=~\"$container_name\"}[1m]))",
     "legendFormat": "vm_tcpdialer_read_calls_total"
    }
   ]
  },
  {
   "title": "vm_tcpdialer_read_timeouts_total/s",
   "type": "timeseries",
   "description": "vm_tcpdialer_read_timeouts_total",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 73 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by () (rate(vm_tcpdialer_read_timeouts_total{cluster=~\"$cluster\",region=~\"$region\",env=~\"$env\",role=\"vm-insert\",instance=~\"$instance\",container_ip=~\"$container_ip\",container_name=~\"$container_name\"}[1m]))",
     "legendFormat": "vm_tcpdialer_read_timeouts_total"
    }
   ]
  },
  {
   "title": "vm_tcpdialer_write_calls_total/s",
   "type": "timeseries",
   "description": "vm_tcpdialer_write_calls_total",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 73 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by () (rate(vm_tcpdialer_write_calls_total{cluster=~\"$cluster\",region=~\"$region\",env=~\"$env\",role=\"vm-insert\",instance=~\"$instance\",container_ip=~\"$container_ip\",container_name=~\"$container_name\"}[1m]))",
     "legendFormat": "vm_tcpdialer_write_calls_total"
    }
   ]
  },
  {
   "title": "vm_tcpdialer_write_timeouts_total/s",
   "type": "timeseries",
   "description": "vm_tcpdialer_write_timeouts_total",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 73 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by () (rate(vm_tcpdialer_write_timeouts_total{cluster=~\"$cluster\",region=~\"$region\",env=~\"$env\",role=\"vm-insert\",instance=~\"$instance\",container_ip=~\"$container_ip\",container_name=~\"$container_name\"}[1m]))",
     "legendFormat": "vm_tcpdialer_write_timeouts_total"
    }
   ]
  },
  {
   "title": "vm_tcpdialer_written_bytes_total/s",
   "type": "timeseries",
   "description": "vm_tcpdialer_written_bytes_total",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 81 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum by () (rate(vm_tcpdialer_written_bytes_total{cluster=~\"$cluster\",region=~\"$region\",env=~\"$env\",role=\"vm-insert\",instance=~\"$instance\",container_ip=~\"$container_ip\",container_name=~\"$container_name\"}[1m]))",
     "legendFormat": "vm_tcpdialer_written_bytes_total"
    }
   ]
  },
  {
   "title": "vm_tcplistener_accepts_total/s",
   "type": "timeseries",
   "description": "vm_tcplistener_accepts_total",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 81 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by () (rate(vm_tcplistener_accepts_total{cluster=~\"$cluster\",region=~\"$region\",env=~\"$env\",role=\"vm-insert\",instance=~\"$instance\",container_ip=~\"$container_ip\",container_name=~\"$container_name\"}[1m]))",
     "legendFormat": "vm_tcplistener_accepts_total"
    }
   ]
  },
  {
   "title": "vm_tcplistener_errors_total/s",
   "type": "timeseries",
   "description": "vm_tcplistener_errors_total",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 81 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by () (rate(vm_tcplistener_errors_total{cluster=~\"$cluster\",region=~\"$region\",env=~\"$env\",role=\"vm-insert\",instance=~\"$instance\",container_ip=~\"$container_ip\",container_name=~\"$container_name\"}[1m]))",
     "legendFormat": "vm_tcplistener_errors_total"
    }
   ]
  },
  {
   "title": "vm_tcplistener_read_bytes_total/s",
   "type": "timeseries",
   "description": "vm_tcplistener_read_bytes_total",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 81 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum by () (rate(vm_tcplistener_read_bytes_total{cluster=~\"$cluster\",region=~\"$region\",env=~\"$env\",role=\"vm-insert\",instance=~\"$instance\",container_ip=~\"$container_ip\",container_name=~\"$container_name\"}[1m]))",
     "legendFormat": "vm_tcplistener_read_bytes_total"
    }
   ]
  },
  {
   "title": "vm_tcplistener_read_calls_total/s",
   "type": "timeseries",
   "description": "vm_tcplistener_read_calls_total",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 89 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by () (rate(vm_tcplistener_read_calls_total{cluster=~\"$cluster\",region=~\"$region\",env=~\"$env\",role=\"vm-insert\",instance=~\"$instance\",container_ip=~\"$container_ip\",container_name=~\"$container_name\"}[1m]))",
     "legendFormat": "vm_tcplistener_read_calls_total"
    }
   ]
  },
  {
   "title": "vm_tcplistener_read_timeouts_total/s",
   "type": "timeseries",
   "description": "vm_tcplistener_read_timeouts_total",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 89 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by () (rate(vm_tcplistener_read_timeouts_total{cluster=~\"$cluster\",region=~\"$region\",env=~\"$env\",role=\"vm-insert\",instance=~\"$instance\",container_ip=~\"$container_ip\",container_name=~\"$container_name\"}[1m]))",
     "legendFormat": "vm_tcplistener_read_timeouts_total"
    }
   ]
  },
  {
   "title": "vm_tcplistener_write_calls_total/s",
   "type": "timeseries",
   "description": "vm_tcplistener_write_calls_total",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 89 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by () (rate(vm_tcplistener_write_calls_total{cluster=~\"$cluster\",region=~\"$region\",env=~\"$env\",role=\"vm-insert\",instance=~\"$instance\",container_ip=~\"$container_ip\",container_name=~\"$container_name\"}[1m]))",
     "legendFormat": "vm_tcplistener_write_calls_total"
    }
   ]
  },
  {
   "title": "vm_tcplistener_write_timeouts_total/s",
   "type": "timeseries",
   "description": "vm_tcplistener_write_timeouts_total",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 89 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by () (rate(vm_tcplistener_write_timeouts_total{cluster=~\"$cluster\",region=~\"$region\",env=~\"$env\",role=\"vm-insert\",instance=~\"$instance\",container_ip=~\"$container_ip\",container_name=~\"$container_name\"}[1m]))",
     "legendFormat": "vm_tcplistener_write_timeouts_total"
    }
   ]
  },
  {
   "title": "vm_tcplistener_written_bytes_total/s",
   "type": "timeseries",
   "description": "vm_tcplistener_written_bytes_total",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 97 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum by () (rate(vm_tcplistener_written_bytes_total{cluster=~\"$cluster\",region=~\"$region\",env=~\"$env\",role=\"vm-insert\",instance=~\"$instance\",container_ip=~\"$container_ip\",container_name=~\"$container_name\"}[1m]))",
     "legendFormat": "vm_tcplistener_written_bytes_total"
    }
   ]
  },
  {
   "title": "vm_tenant_inserted_rows_total/s",
   "type": "timeseries",
   "description": "vm_tenant_inserted_rows_total",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 97 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by () (rate(vm_tenant_inserted_rows_total{cluster=~\"$cluster\",region=~\"$region\",env=~\"$env\",role=\"vm-insert\",instance=~\"$instance\",container_ip=~\"$container_ip\",container_name=~\"$container_name\"}[1m]))",
     "legendFormat": "vm_tenant_inserted_rows_total"
    }
   ]
  },
  {
   "title": "vm_cache_chars_current",
   "type": "timeseries",
   "description": "vm_cache_chars_current",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 97 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(vm_cache_chars_current{cluster=~\"$cluster\",region=~\"$region\",env=~\"$env\",role=\"vm-insert\",instance=~\"$instance\",container_ip=~\"$container_ip\",container_name=~\"$container_name\"})",
     "legendFormat": "vm_cache_chars_current"
    }
   ]
  },
  {
   "title": "vm_cache_entries",
   "type": "timeseries",
   "description": "vm_cache_entries",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 97 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(vm_cache_entries{cluster=~\"$cluster\",region=~\"$region\",env=~\"$env\",role=\"vm-insert\",instance=~\"$instance\",container_ip=~\"$container_ip\",container_name=~\"$container_name\"})",
     "legendFormat": "vm_cache_entries"
    }
   ]
  },
  {
   "title": "vm_rpc_rows_pending",
   "type": "timeseries",
   "description": "vm_rpc_rows_pending",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 105 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(vm_rpc_rows_pending{cluster=~\"$cluster\",region=~\"$region\",env=~\"$env\",role=\"vm-insert\",instance=~\"$instance\",container_ip=~\"$container_ip\",container_name=~\"$container_name\"})",
     "legendFormat": "vm_rpc_rows_pending"
    }
   ]
  },
  {
   "title": "vm_tcpdialer_conns",
   "type": "timeseries",
   "description": "vm_tcpdialer_conns",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 105 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(vm_tcpdialer_conns{cluster=~\"$cluster\",region=~\"$region\",env=~\"$env\",role=\"vm-insert\",instance=~\"$instance\",container_ip=~\"$container_ip\",container_name=~\"$container_name\"})",
     "legendFormat": "vm_tcpdialer_conns"
    }
   ]
  },
  {
   "title": "vm_tcplistener_conns",
   "type": "timeseries",
   "description": "vm_tcplistener_conns",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 105 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(vm_tcplistener_conns{cluster=~\"$cluster\",region=~\"$region\",env=~\"$env\",role=\"vm-insert\",instance=~\"$instance\",container_ip=~\"$container_ip\",container_name=~\"$container_name\"})",
     "legendFormat": "vm_tcplistener_conns"
    }
   ]
  },
  {
   "title": "vm_rpc_buf_pending_bytes",
   "type": "timeseries",
   "description": "vm_rpc_buf_pending_bytes",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 105 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum(vm_rpc_buf_pending_bytes{cluster=~\"$cluster\",region=~\"$region\",env=~\"$env\",role=\"vm-insert\",instance=~\"$instance\",container_ip=~\"$container_ip\",container_name=~\"$container_name\"})",
     "legendFormat": "vm_rpc_buf_pending_bytes"
    }
   ]
  },
  {
   "title": "vm_http_request_duration_seconds_bucket",
   "type": "heatmap",
   "description": "vm_http_request_duration_seconds_bucket",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 113 },
   "targets": [
    {
     "expr": "sum(increase(label_replace(vm_http_request_duration_seconds_bucket{cluster=~\"$cluster\",region=~\"$region\",env=~\"$env\",role=\"vm-insert\",instance=~\"$instance\",container_ip=~\"$container_ip\",container_name=~\"$container_name\"}, \"le\", \"$1\", \"vmrange\", \"([^\\\\n]+)\\\\.\\\\.\\\\.([^\\\\n]+)\")[1m])) by (le)",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "vm_rows_per_insert_bucket",
   "type": "heatmap",
   "description": "vm_rows_per_insert_bucket",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 113 },
   "targets": [
    {
     "expr": "sum(increase(label_replace(vm_rows_per_insert_bucket{cluster=~\"$cluster\",region=~\"$region\",env=~\"$env\",role=\"vm-insert\",instance=~\"$instance\",container_ip=~\"$container_ip\",container_name=~\"$container_name\"}, \"le\", \"$1\", \"vmrange\", \"([^\\\\n]+)\\\\.\\\\.\\\\.([^\\\\n]+)\")[1m])) by (le)",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "vminsert_request_duration_seconds_bucket",
   "type": "heatmap",
   "description": "vminsert_request_duration_seconds_bucket",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 113 },
   "targets": [
    {
     "expr": "sum(increase(label_replace(vminsert_request_duration_seconds_bucket{cluster=~\"$cluster\",region=~\"$region\",env=~\"$env\",role=\"vm-insert\",instance=~\"$instance\",container_ip=~\"$container_ip\",container_name=~\"$container_name\"}, \"le\", \"$1\", \"vmrange\", \"([^\\\\n]+)\\\\.\\\\.\\\\.([^\\\\n]+)\")[1m])) by (le)",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "vm_concurrent_insert_capacity",
   "type": "stat",
   "description": "vm_concurrent_insert_capacity",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 121 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(vm_concurrent_insert_capacity{instance=~\"$instance\",container_name=~\"$container_name\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "vm_concurrent_insert_current",
   "type": "stat",
   "description": "vm_concurrent_insert_current",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 121 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(vm_concurrent_insert_current{instance=~\"$instance\",container_name=~\"$container_name\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "vm_rpc_vmstorage_is_reachable",
   "type": "stat",
   "description": "vm_rpc_vmstorage_is_reachable",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 121 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(vm_rpc_vmstorage_is_reachable{instance=~\"$instance\",container_name=~\"$container_name\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "vm_rpc_vmstorage_is_read_only",
   "type": "stat",
   "description": "vm_rpc_vmstorage_is_read_only",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 121 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(vm_rpc_vmstorage_is_read_only{instance=~\"$instance\",container_name=~\"$container_name\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "vm_promscrape_config_last_reload_successful",
   "type": "stat",
   "description": "vm_promscrape_config_last_reload_successful",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 129 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(vm_promscrape_config_last_reload_successful{instance=~\"$instance\",container_name=~\"$container_name\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "vm_cache_chars_max",
   "type": "stat",
   "description": "vm_cache_chars_max",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 129 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(vm_cache_chars_max{instance=~\"$instance\",container_name=~\"$container_name\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "vm_promscrape_config_last_reload_success_timestamp_seconds",
   "type": "stat",
   "description": "vm_promscrape_config_last_reload_success_timestamp_seconds",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 113 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "time()-min(vm_promscrape_config_last_reload_success_timestamp_seconds{instance=~\"$instance\",container_name=~\"$container_name\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "not added metrics", "type": "text", "gridPos": { "h": 8, "w": 6, "x": 6, "y": 129 }, "options": { "content": "* vm_app_version\n" } }
 ]
}