version: '3'
services:
  vm-restore-historical-cluster-0:
    container_name: "vm-restore-historical-cluster-0"
    image: "victoriametrics/vmrestore:v1.95.1"
    pull_policy: if_not_present
    command:
      - "-concurrency=1"
      - "-maxBytesPerSecond=1GB"
      - "-memory.allowedPercent=80"
      - "-src=s3://${AWS_BUCKET}/metrics/vmstorage/backup/2023-12-05/sharding-00/"
      - "-storageDataPath=/data/sharding-00-restore/"
      - -pushmetrics.extraLabel='region="HK",env="formal",cluster="historical-cluster",role="vm-restore"'
      - -pushmetrics.interval=5s
      - -pushmetrics.url=http://host.docker.internal:38480/insert/0/prometheus/api/v1/import/prometheus
      - "-httpListenAddr=:18421"
      - "-loggerDisableTimestamps"
      - "-loggerFormat=json"
      - "-loggerLevel=INFO"
      - "-loggerOutput=stdout"
    environment:
      GOMAXPROCS: 1
      # must set .env file first
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
      AWS_REGION: ${AWS_REGION}
      AWS_BUCKET: ${AWS_BUCKET}
    volumes:
      - type: bind
        source: ../data/
        target: /data/
    deploy:
      resources:
        limits:
          cpus: "0.1"
          memory: 128M
